import { Page } from '@playwright/test';

export const WwwPageLocators = {
  // Uniqueness: verify | Stability: stable — XPath locator | Fallback: see all strategies in object repository
  solutionsButton: (page: Page) => page.locator('xpath=//button[normalize-space(text())=\'Solutions\']').filter({ visible: true }).first(),
  // Uniqueness: verify | Stability: stable — XPath locator | Fallback: see all strategies in object repository
  strongCustomerAuthenticationLink: (page: Page) => page.locator('xpath=//a[@aria-label=\'Strong Customer Authentication Enable fast and secure account access with multi-factor authentication solutions that protect against account takeover attacks\']').filter({ visible: true }).first(),
  fidoHardwareAuthenticatorsStLink: (page: Page) => page.locator('xpath=//a[@aria-label=\'FIDO Hardware Authenticators Stop account takeover with a phishing resistant, passwordless solution that enables faster logins\']').filter({ visible: true }).first(),
  resourcesButton: (page: Page) => page.locator('xpath=//button[normalize-space(text())=\'Resources\']').filter({ visible: true }).first(),
  pricingButton: (page: Page) => page.locator('xpath=//button[normalize-space(text())=\'Pricing\']').filter({ visible: true }).first(),
  companyButton: (page: Page) => page.locator('xpath=//button[normalize-space(text())=\'Company\']').filter({ visible: true }).first(),
  contactUsLink: (page: Page) => page.locator('xpath=//a[normalize-space(text())=\'Contact Us\']').filter({ visible: true }).first(),
  productsButton: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Header Navigation']//button[normalize-space(text())='Products']"),
  requestDemoLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main header call to action buttonsw']//a[normalize-space(text())='Request demo']"),
  oneSpanSignLoginButton: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Top header navigation']//button[normalize-space(text())='OneSpan Sign Login']"),
  supportButton: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Top header navigation']//button[normalize-space(text())='Support']"),
  searchLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Top header navigation']//a[normalize-space(text())='Search']"),
  closeButton: (page: Page): Locator => page.locator("xpath=//button[normalize-space(text())='Close']"),
  emailInput: (page: Page): Locator => page.locator("xpath=//input[@id='Email']"),
  countryDropdown: (page: Page): Locator => page.locator("xpath=//select[@id='Country']"),
  firstNameInput: (page: Page): Locator => page.locator("xpath=//input[@id='FirstName']"),
  lastNameInput: (page: Page): Locator => page.locator("xpath=//input[@id='LastName']"),
  companyInput: (page: Page): Locator => page.locator("xpath=//input[@id='Company']"),
  industryDropdown: (page: Page): Locator => page.locator("xpath=//select[@id='Industry']"),
  phoneInput: (page: Page): Locator => page.locator("xpath=//input[@id='Phone']"),
  businessInterestDropdown: (page: Page): Locator => page.locator("xpath=//select[@id='Business_Interest__c']"),
  commentsInput: (page: Page): Locator => page.locator("xpath=//textarea[@id='Web_Form_Comments__c']"),
  submitButton: (page: Page): Locator => page.locator("xpath=//button[normalize-space(text())='Submit']"),
  fidoHardwareAuthenticatorsLink: (page: Page): Locator => page.locator('xpath=//a[contains(normalize-space(text()),
  secureTransactionSigningLink: (page: Page): Locator => page.locator('xpath=//a[contains(normalize-space(text()),
  blogLink: (page: Page): Locator => page.locator('xpath=//a[normalize-space(text())="Blog"]'),
  cybersecurityPricingLink: (page: Page): Locator => page.locator('xpath=//a[contains(normalize-space(text()),
  careersLink: (page: Page): Locator => page.locator('xpath=//a[normalize-space(text())="Careers"]'),
  industrySelect: (page: Page): Locator => page.locator('xpath=//select[@id="Industry"]'),
  countrySelect: (page: Page): Locator => page.locator('xpath=//select[@id="Country"]'),
  businessInterestSelect: (page: Page): Locator => page.locator('xpath=//select[@id="Business_Interest__c"]'),
  communityPortalLink: (page: Page) => page.locator('xpath=//a[normalize-space(text())=\'Community Portal\']').filter({ visible: true }).first(),
  mainLogo: (page: Page): Locator => page.locator("xpath=//header//a[@aria-label='OneSpan' or contains(@class,
  mainNavigation: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Navigation' or @id='main-nav']"),
  productsNavLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Navigation' or @id='main-nav']//a[normalize-space(text())='Products' or @aria-label='Products']"),
  solutionsNavLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Navigation' or @id='main-nav']//a[normalize-space(text())='Solutions' or @aria-label='Solutions']"),
  resourcesNavLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Navigation' or @id='main-nav']//a[normalize-space(text())='Resources' or @aria-label='Resources']"),
  companyNavLink: (page: Page): Locator => page.locator("xpath=//nav[@aria-label='Main Navigation' or @id='main-nav']//a[normalize-space(text())='Company' or @aria-label='Company']"),
  searchButton: (page: Page): Locator => page.locator("xpath=//header//button[@data-testid='search-btn' or @aria-label='Search' or contains(@class,
  loginButton: (page: Page): Locator => page.locator("xpath=//header//a[@data-testid='login-btn' or normalize-space(text())='Sign In' or normalize-space(text())='Login']"),
  requestDemoButton: (page: Page): Locator => page.locator("xpath=//a[@data-testid='request-demo' or normalize-space(text())='Request a Demo' or normalize-space(text())='Get Started']"),
  acceptCookiesButton: (page: Page): Locator => page.locator("xpath=//*[@id='cookie-banner' or @data-testid='cookie-consent']//button[normalize-space(text())='Accept' or @aria-label='Accept Cookies']"),
  mainHeading: (page: Page): Locator => page.locator("xpath=//main//h1[1] | //section[1]//h1[1]"),
  searchInput: (page: Page): Locator => page.locator("xpath=//input[@data-testid='search-input' or @placeholder='Search' or @aria-label='Search']"),
  footerSection: (page: Page): Locator => page.locator("xpath=//footer[@id='footer' or @role='contentinfo']"),
  regionSelector: (page: Page): Locator => page.locator("xpath=//button[@data-testid='region-selector' or @aria-label='Select Region' or contains(@class,
  closeModalButton: (page: Page): Locator => page.locator("xpath=//button[@data-testid='close-modal' or @aria-label='Close' or contains(@class,
  solutionText: (page: Page): Locator => page.locator('xpath=//*[contains(normalize-space(text()),
  fidoAuthenticatorText: (page: Page): Locator => page.locator('xpath=//*[contains(normalize-space(text()),
  mobileAuthenticationText: (page: Page): Locator => page.locator('xpath=//*[contains(normalize-space(text()),
};
