import { Page } from '@playwright/test';

/**
 * Page Object: Digital Product Engineering Services, Product Engineering Company
 * URL: https://www.nousinfosystems.com/services/digital-product-engineering
 * Generated by NAT20 Autonomous Testing Platform
 */
export class DigitalProductEngineeringPage {
  constructor(readonly page: Page) {}

  readonly url = 'https://www.nousinfosystems.com/services/digital-product-engineering';
  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly your_nameField = this.page.locator('input[name="your-name"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly your_subjectField = this.page.locator('input[name="your-subject"]').first();
  readonly your_messageField = this.page.locator('textarea[name="your-message"]').first();
  readonly by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly _1_btn = this.page.locator('button:has-text("1")').first();
  readonly _1000_product_releases_across_industries_btn = this.page.locator('button:has-text("1000+ product releases across industries")').first();
  readonly performance_driven_development_btn = this.page.locator('button:has-text("Performance-driven development")').first();
  readonly proven_engineering_frameworks_methodologies_btn = this.page.locator('button:has-text("Proven engineering frameworks methodologies")').first();
  readonly diversified_technology_expertise_btn = this.page.locator('button:has-text("Diversified technology expertise")').first();
  readonly flexible_engagement_and_mature_process_models_btn = this.page.locator('button:has-text("Flexible engagement and mature process models")').first();
  readonly submit_btn = this.page.locator('button[type="submit"], input[type="submit"]').first();
  readonly btn = this.page.locator('button[type="submit"], input[type="submit"]').first();

  async verifyHeading(expected = 'Build future-proof software products with digital engineering services'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.your_nameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_nameField.fill('');
    await this.your_nameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.your_subjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_subjectField.fill('');
    await this.your_subjectField.fill(value);
  }

  async fillYourMessage(value = '25'): Promise<void> {
    await this.your_messageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_messageField.fill('');
    await this.your_messageField.fill(value);
  }

  async fillBySubmittingThisFormYouAgreeToBeContactedByNousInfosystemsViaEmailPhoneAndSmsByOptingInForTextMessagesYouConsentToReceiveAppointmentRemindersAndUpdatesAtTheNumberProvidedMessageFrequencyVariesMsgDataRatesMayApplyReplyStopToUnsubscribeOrHelpForHelpViewOurPrivacyPolicyAndTCForDetails(value = 'Test Value'): Promise<void> {
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.waitFor({ state: 'visible', timeout: 8000 });
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill('');
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async click1(): Promise<void> {
    await this._1_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._1_btn.click();
  }

  async click1000ProductReleasesAcrossIndustries(): Promise<void> {
    await this._1000_product_releases_across_industries_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._1000_product_releases_across_industries_btn.click();
  }

  async clickPerformanceDrivenDevelopment(): Promise<void> {
    await this.performance_driven_development_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.performance_driven_development_btn.click();
  }

  async clickProvenEngineeringFrameworksMethodologies(): Promise<void> {
    await this.proven_engineering_frameworks_methodologies_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.proven_engineering_frameworks_methodologies_btn.click();
  }

  async clickDiversifiedTechnologyExpertise(): Promise<void> {
    await this.diversified_technology_expertise_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.diversified_technology_expertise_btn.click();
  }

  async clickFlexibleEngagementAndMatureProcessModels(): Promise<void> {
    await this.flexible_engagement_and_mature_process_models_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.flexible_engagement_and_mature_process_models_btn.click();
  }

  async clickSubmit(): Promise<void> {
    await this.submit_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.submit_btn.click();
  }

  async clickBtn(): Promise<void> {
    await this.btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.btn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto(this.url, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'digital_product_engineering'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
