
// Generated by NAT20 — do not edit
module.exports = {
  testDir: "C:/Users/chandramouli/Downloads/Nat20-main/Nat20-main/.autotest-tmp/run_1774869767197/tests/specs",
  testMatch: ['**/*.spec.ts'],
  timeout: 60000,
  retries: 0,
  workers: 1,
  use: {
    baseURL: "https://amerisure.com",
    headless: false,
    viewport: { width: 1280, height: 800 },
    screenshot: 'only-on-failure',
    video: 'off',
    launchOptions: { slowMo: 100 },
  },
  reporter: [['json', { outputFile: "C:/Users/chandramouli/Downloads/Nat20-main/Nat20-main/.autotest-tmp/run_1774869767197/results.json" }], ['line']],
  projects: [{ name: 'chromium' }],
};
