import { Page } from '@playwright/test';

/**
 * Page Object: Case Studies | Artizent
 * URL: https://artizent.com/insights/case-studies
 * Generated by NAT20 Autonomous Testing Platform
 */
export class CaseStudiesPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly services_btn = this.page.locator('button:has-text("Services")').first();
  readonly astra_btn = this.page.locator('button:has-text("Astra")').first();
  readonly about_us_btn = this.page.locator('button:has-text("About Us")').first();
  readonly see_all_25_btn = this.page.locator('button:has-text("See all (25)")').first();
  readonly financial_services_6_btn = this.page.locator('button:has-text("Financial Services (6)")').first();
  readonly insurance_4_btn = this.page.locator('button:has-text("Insurance (4)")').first();
  readonly digital_platforms_8_btn = this.page.locator('button:has-text("Digital Platforms (8)")').first();
  readonly industrial_consumer_7_btn = this.page.locator('button:has-text("Industrial & Consumer (7)")').first();

  async verifyHeading(expected = 'AI in production. Long before it was fashionable.'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async clickServices(): Promise<void> {
    await this.services_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.services_btn.click();
  }

  async clickAstra(): Promise<void> {
    await this.astra_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.astra_btn.click();
  }

  async clickAboutUs(): Promise<void> {
    await this.about_us_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.about_us_btn.click();
  }

  async clickSeeAll25(): Promise<void> {
    await this.see_all_25_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.see_all_25_btn.click();
  }

  async clickFinancialServices6(): Promise<void> {
    await this.financial_services_6_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.financial_services_6_btn.click();
  }

  async clickInsurance4(): Promise<void> {
    await this.insurance_4_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.insurance_4_btn.click();
  }

  async clickDigitalPlatforms8(): Promise<void> {
    await this.digital_platforms_8_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.digital_platforms_8_btn.click();
  }

  async clickIndustrialConsumer7(): Promise<void> {
    await this.industrial_consumer_7_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.industrial_consumer_7_btn.click();
  }

  async clickNavCaseStudies(): Promise<void> {
    await this.page.getByRole('link', { name: 'Case Studies' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavGetInTouch(): Promise<void> {
    await this.page.getByRole('link', { name: 'Get in Touch' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/insights/case-studies', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
