import { Page } from '@playwright/test';

/**
 * Page Object: Contact Us | Artizent
 * URL: https://artizent.com/contact
 * Generated by NAT20 Autonomous Testing Platform
 */
export class ContactPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly nameField = this.page.locator('[placeholder="Name"]').first();
  readonly emailField = this.page.locator('[placeholder="johnsmith@artizent.com"]').first();
  readonly how_can_we_helpField = this.page.locator('[placeholder="Tell us about your use case, timeline, or any questions..."]').first();
  readonly services_btn = this.page.locator('button:has-text("Services")').first();
  readonly astra_btn = this.page.locator('button:has-text("Astra")').first();
  readonly about_us_btn = this.page.locator('button:has-text("About Us")').first();
  readonly send_messagesend_message_btn = this.page.locator('button[type="submit"], input[type="submit"]').first();

  async verifyHeading(expected = 'Let\'s build what\'s next'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillName(value = 'John Doe'): Promise<void> {
    await this.nameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.nameField.fill('');
    await this.nameField.fill(value);
  }

  async fillEmail(value = 'test@example.com'): Promise<void> {
    await this.emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.emailField.fill('');
    await this.emailField.fill(value);
  }

  async fillHowCanWeHelp(value = 'Test Value'): Promise<void> {
    await this.how_can_we_helpField.waitFor({ state: 'visible', timeout: 8000 });
    await this.how_can_we_helpField.fill('');
    await this.how_can_we_helpField.fill(value);
  }

  async clickServices(): Promise<void> {
    await this.services_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.services_btn.click();
  }

  async clickAstra(): Promise<void> {
    await this.astra_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.astra_btn.click();
  }

  async clickAboutUs(): Promise<void> {
    await this.about_us_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.about_us_btn.click();
  }

  async clickSendMessagesendMessage(): Promise<void> {
    await this.send_messagesend_message_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.send_messagesend_message_btn.click();
  }

  async clickNavCaseStudies(): Promise<void> {
    await this.page.getByRole('link', { name: 'Case Studies' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavGetInTouch(): Promise<void> {
    await this.page.getByRole('link', { name: 'Get in Touch' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/contact', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
