import { Page } from '@playwright/test';

/**
 * Page Object: An insurance policy administration platform, delivered in under a year using an AI native, secure development process | Artizent Case Study
 * URL: https://artizent.com/insights/case-studies/full-platform-at-60-percent-cost
 * Generated by NAT20 Autonomous Testing Platform
 */
export class FullPlatformAt60PercentCostPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly services_btn = this.page.locator('button:has-text("Services")').first();
  readonly astra_btn = this.page.locator('button:has-text("Astra")').first();
  readonly about_us_btn = this.page.locator('button:has-text("About Us")').first();

  async verifyHeading(expected = 'An insurance policy administration platform, delivered in under a year using an AI native, secure development process'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async clickServices(): Promise<void> {
    await this.services_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.services_btn.click();
  }

  async clickAstra(): Promise<void> {
    await this.astra_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.astra_btn.click();
  }

  async clickAboutUs(): Promise<void> {
    await this.about_us_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.about_us_btn.click();
  }

  async clickNavCaseStudies(): Promise<void> {
    await this.page.getByRole('link', { name: 'Case Studies' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavGetInTouch(): Promise<void> {
    await this.page.getByRole('link', { name: 'Get in Touch' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/insights/case-studies/full-platform-at-60-percent-cost', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
