import { Page } from '@playwright/test';

/**
 * Page Object: Artizent (formerly known as Nous Infosystems) | The Engineering Partner for Mission Critical AI
 * URL: https://artizent.com/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class HomePage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly services_btn = this.page.locator('button:has-text("Services")').first();
  readonly astra_btn = this.page.locator('button:has-text("Astra")').first();
  readonly about_us_btn = this.page.locator('button:has-text("About Us")').first();
  readonly software_product_engineering_btn = this.page.locator('#practice-tab-spe').first();
  readonly data_analytics_btn = this.page.locator('#practice-tab-data').first();
  readonly agentic_enterprise_btn = this.page.locator('#practice-tab-agents').first();
  readonly cloud_cybersecurity_btn = this.page.locator('#practice-tab-infra').first();

  async verifyHeading(expected = 'The engineering partner for mission critical AI'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async clickServices(): Promise<void> {
    await this.services_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.services_btn.click();
  }

  async clickAstra(): Promise<void> {
    await this.astra_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.astra_btn.click();
  }

  async clickAboutUs(): Promise<void> {
    await this.about_us_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.about_us_btn.click();
  }

  async clickSoftwareProductEngineering(): Promise<void> {
    await this.software_product_engineering_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.software_product_engineering_btn.click();
  }

  async clickDataAnalytics(): Promise<void> {
    await this.data_analytics_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.data_analytics_btn.click();
  }

  async clickAgenticEnterprise(): Promise<void> {
    await this.agentic_enterprise_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.agentic_enterprise_btn.click();
  }

  async clickCloudCybersecurity(): Promise<void> {
    await this.cloud_cybersecurity_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.cloud_cybersecurity_btn.click();
  }

  async clickNavCaseStudies(): Promise<void> {
    await this.page.getByRole('link', { name: 'Case Studies' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavGetInTouch(): Promise<void> {
    await this.page.getByRole('link', { name: 'Get in Touch' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
