import { Page } from '@playwright/test';

/**
 * Page Object: Software & Product Engineering | Artizent
 * URL: https://artizent.com/services/software-product-engineering
 * Generated by NAT20 Autonomous Testing Platform
 */
export class SoftwareProductEngineeringPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly services_btn = this.page.locator('button:has-text("Services")').first();
  readonly astra_btn = this.page.locator('button:has-text("Astra")').first();
  readonly about_us_btn = this.page.locator('button:has-text("About Us")').first();
  readonly _01you_ship_faster_and_keep_shipping_faster_btn = this.page.locator('button:has-text("01You ship faster, and keep shipping faster.")').first();
  readonly _02your_products_get_smarter_in_production_btn = this.page.locator('button:has-text("02Your products get smarter in production.")').first();
  readonly _03quality_and_compliance_hold_as_you_scale_btn = this.page.locator('button:has-text("03Quality and compliance hold as you scale.")').first();
  readonly _04legacy_stops_being_the_thing_that_slows_you_down_btn = this.page.locator('button:has-text("04Legacy stops being the thing that slows you down.")').first();
  readonly does_the_model_stay_with_us_after_the_engagement_btn = this.page.locator('#faq-btn-0').first();

  async verifyHeading(expected = 'Build, modernize, and scale software at AI speed'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async clickServices(): Promise<void> {
    await this.services_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.services_btn.click();
  }

  async clickAstra(): Promise<void> {
    await this.astra_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.astra_btn.click();
  }

  async clickAboutUs(): Promise<void> {
    await this.about_us_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.about_us_btn.click();
  }

  async clickP01youShipFasterAndKeepShippingFaster(): Promise<void> {
    await this._01you_ship_faster_and_keep_shipping_faster_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._01you_ship_faster_and_keep_shipping_faster_btn.click();
  }

  async clickP02yourProductsGetSmarterInProduction(): Promise<void> {
    await this._02your_products_get_smarter_in_production_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._02your_products_get_smarter_in_production_btn.click();
  }

  async clickP03qualityAndComplianceHoldAsYouScale(): Promise<void> {
    await this._03quality_and_compliance_hold_as_you_scale_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._03quality_and_compliance_hold_as_you_scale_btn.click();
  }

  async clickP04legacyStopsBeingTheThingThatSlowsYouDown(): Promise<void> {
    await this._04legacy_stops_being_the_thing_that_slows_you_down_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._04legacy_stops_being_the_thing_that_slows_you_down_btn.click();
  }

  async clickDoesTheModelStayWithUsAfterTheEngagement(): Promise<void> {
    await this.does_the_model_stay_with_us_after_the_engagement_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.does_the_model_stay_with_us_after_the_engagement_btn.click();
  }

  async clickNavCaseStudies(): Promise<void> {
    await this.page.getByRole('link', { name: 'Case Studies' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavGetInTouch(): Promise<void> {
    await this.page.getByRole('link', { name: 'Get in Touch' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/services/software-product-engineering', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
