import { Page } from '@playwright/test';

/**
 * Page Object: Quality Engineering Services | Software Quality Engineering
 * URL: https://www.nousinfosystems.com/services/quality-engineering
 * Generated by NAT20 Autonomous Testing Platform
 */
export class QualityEngineeringPage {
  constructor(readonly page: Page) {}

  readonly url = 'https://www.nousinfosystems.com/services/quality-engineering';
  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly your_nameField = this.page.locator('input[name="your-name"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly your_subjectField = this.page.locator('input[name="your-subject"]').first();
  readonly your_messageField = this.page.locator('textarea[name="your-message"]').first();
  readonly by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly previous_btn = this.page.locator('button:has-text("Previous")').first();
  readonly next_btn = this.page.locator('button:has-text("Next")').first();
  readonly _1_btn = this.page.locator('button:has-text("1")').first();
  readonly _2_btn = this.page.locator('button:has-text("2")').first();
  readonly _25_years_of_experience_in_the_software_industry_btn = this.page.locator('button:has-text("25+ years of experience in the software industry")').first();
  readonly in_house_r_d_labs_test_automation_framework_btn = this.page.locator('button:has-text("In-house R&D labs, test automation framework")').first();
  readonly strong_partnership_with_best_in_class_testing_tools_btn = this.page.locator('button:has-text("Strong partnership with best-in-class testing tools")').first();
  readonly reusable_assets_for_the_quick_and_easy_adoption_btn = this.page.locator('button:has-text("Reusable assets for the quick and easy adoption")').first();

  async verifyHeading(expected = 'Scalable quality engineering services for accelerated digital transformation'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.your_nameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_nameField.fill('');
    await this.your_nameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.your_subjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_subjectField.fill('');
    await this.your_subjectField.fill(value);
  }

  async fillYourMessage(value = '25'): Promise<void> {
    await this.your_messageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_messageField.fill('');
    await this.your_messageField.fill(value);
  }

  async fillBySubmittingThisFormYouAgreeToBeContactedByNousInfosystemsViaEmailPhoneAndSmsByOptingInForTextMessagesYouConsentToReceiveAppointmentRemindersAndUpdatesAtTheNumberProvidedMessageFrequencyVariesMsgDataRatesMayApplyReplyStopToUnsubscribeOrHelpForHelpViewOurPrivacyPolicyAndTCForDetails(value = 'Test Value'): Promise<void> {
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.waitFor({ state: 'visible', timeout: 8000 });
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill('');
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async clickPrevious(): Promise<void> {
    await this.previous_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.previous_btn.click();
  }

  async clickNext(): Promise<void> {
    await this.next_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.next_btn.click();
  }

  async click1(): Promise<void> {
    await this._1_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._1_btn.click();
  }

  async click2(): Promise<void> {
    await this._2_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._2_btn.click();
  }

  async click25YearsOfExperienceInTheSoftwareIndustry(): Promise<void> {
    await this._25_years_of_experience_in_the_software_industry_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._25_years_of_experience_in_the_software_industry_btn.click();
  }

  async clickInHouseRDLabsTestAutomationFramework(): Promise<void> {
    await this.in_house_r_d_labs_test_automation_framework_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.in_house_r_d_labs_test_automation_framework_btn.click();
  }

  async clickStrongPartnershipWithBestInClassTestingTools(): Promise<void> {
    await this.strong_partnership_with_best_in_class_testing_tools_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.strong_partnership_with_best_in_class_testing_tools_btn.click();
  }

  async clickReusableAssetsForTheQuickAndEasyAdoption(): Promise<void> {
    await this.reusable_assets_for_the_quick_and_easy_adoption_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.reusable_assets_for_the_quick_and_easy_adoption_btn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto(this.url, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'quality_engineering'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
