import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Bot, Eye, Settings, Accessibility, Code2, Brain,
  GitBranch, BarChart3, Shield, Users, Lock, ShieldCheck,
  AlertTriangle, EyeOff, Zap, ArrowRight, CheckCircle2,
  Sparkles, TrendingUp,
} from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useBranding } from "@/contexts/BrandingContext";

type CodeToken = { text: string; color: string };
type CodeLine  = { indent: number; tokens: CodeToken[] };

const CODE_LINES: CodeLine[] = [
  { indent: 0, tokens: [{ text: "// Generated by ASTRA AI", color: "#6b7280" }] },
  { indent: 0, tokens: [
    { text: "test", color: "#818cf8" },
    { text: "('User login flow', ", color: "#374151" },
    { text: "async", color: "#818cf8" },
    { text: " ({ page }) => {", color: "#374151" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#374151" },
    { text: "page", color: "#3b82f6" },
    { text: ".goto(", color: "#374151" },
    { text: "'/login'", color: "#059669" },
    { text: ")", color: "#374151" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#374151" },
    { text: "page", color: "#3b82f6" },
    { text: ".fill(", color: "#374151" },
    { text: "'#email'", color: "#059669" },
    { text: ", user.email)", color: "#374151" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#374151" },
    { text: "page", color: "#3b82f6" },
    { text: ".fill(", color: "#374151" },
    { text: "'#password'", color: "#059669" },
    { text: ", user.password)", color: "#374151" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#374151" },
    { text: "page", color: "#3b82f6" },
    { text: ".click(", color: "#374151" },
    { text: "'button[type=\"submit\"]'", color: "#059669" },
    { text: ")", color: "#374151" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#374151" },
    { text: "expect", color: "#ec4899" },
    { text: "(page).toHaveURL(", color: "#374151" },
    { text: "'/dashboard'", color: "#059669" },
    { text: ")", color: "#374151" },
  ]},
  { indent: 0, tokens: [{ text: "})", color: "#374151" }] },
];

export default function LandingPage() {
  const [, setLocation] = useLocation();

  /* ── All state UNTOUCHED ── */
  const [email, setEmail]                = useState("");
  const [password, setPassword]          = useState("");
  const [showPassword, setShowPassword]  = useState(false);
  const [isLoading, setIsLoading]        = useState(false);
  const { toast }  = useToast();
  const { brand }  = useBranding();

  const [mustChange,      setMustChange]      = useState(false);
  const [newPassword,     setNewPassword]     = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [showNewPw,       setShowNewPw]       = useState(false);
  const [showConfirmPw,   setShowConfirmPw]   = useState(false);
  const [isChanging,      setIsChanging]      = useState(false);

  /* ── Auth redirect UNTOUCHED ── */
  useEffect(() => {
    const isAuthenticated = localStorage.getItem("isAuthenticated") === "true";
    if (isAuthenticated) setLocation("/dashboard");
  }, [setLocation]);

  /* ── Login handler UNTOUCHED ── */
  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      const res  = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: email.trim(), password }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        localStorage.setItem("isAuthenticated", "true");
        localStorage.setItem("currentUser", JSON.stringify({
          id: data.userId, username: data.username, tenantId: data.tenantId,
        }));
        if (data.mustChangePassword) {
          setMustChange(true);
        } else {
          setLocation("/dashboard");
        }
      } else {
        toast({ variant: "destructive", title: "Login failed", description: data.error || "Invalid credentials" });
      }
    } catch (error: any) {
      toast({ variant: "destructive", title: "Login failed", description: error.message || "Please try again" });
    } finally {
      setIsLoading(false);
    }
  };

  /* ── Change-password handler UNTOUCHED ── */
  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newPassword.length < 8) {
      toast({ title: "Too short", description: "Password must be at least 8 characters", variant: "destructive" });
      return;
    }
    if (newPassword !== confirmPassword) {
      toast({ title: "Mismatch", description: "Passwords do not match", variant: "destructive" });
      return;
    }
    if (newPassword === password) {
      toast({ title: "Same password", description: "New password must be different from the temporary one", variant: "destructive" });
      return;
    }
    setIsChanging(true);
    try {
      const res  = await fetch("/api/auth/change-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ currentPassword: password, newPassword }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        toast({ title: "Password updated", description: "Your new password is set. Welcome!" });
        setLocation("/dashboard");
      } else {
        toast({ title: "Failed", description: data.error || "Could not update password", variant: "destructive" });
      }
    } catch {
      toast({ title: "Network error", description: "Could not reach the server", variant: "destructive" });
    } finally {
      setIsChanging(false);
    }
  };

  /* ── Feature data ── */
  const features = [
    { icon: <Bot className="w-[22px] h-[22px]" />,          title: "AI Agent Testing",        description: "Autonomous agents analyze your apps and generate comprehensive test cases — no scripts needed.",      grad: "from-indigo-500 to-violet-500" },
    { icon: <Eye className="w-[22px] h-[22px]" />,           title: "Visual Regression",        description: "Compare Figma designs with live websites. Detect layout, color, and spacing discrepancies instantly.", grad: "from-violet-500 to-purple-500" },
    { icon: <Settings className="w-[22px] h-[22px]" />,      title: "Functional Testing",       description: "Test clicks, form submissions, navigation flows, and user interactions end-to-end, automatically.",   grad: "from-blue-500 to-indigo-500" },
    { icon: <Accessibility className="w-[22px] h-[22px]" />, title: "Accessibility Compliance", description: "Automated WCAG AA compliance testing. Catch contrast issues, keyboard nav, and screen reader gaps.",   grad: "from-cyan-500 to-blue-500" },
    { icon: <Code2 className="w-[22px] h-[22px]" />,         title: "Code Review & QA",         description: "Intelligent code analysis with automated quality checks. Review PRs and surface issues early.",         grad: "from-emerald-500 to-cyan-500" },
    { icon: <Brain className="w-[22px] h-[22px]" />,         title: "Agentic RAG Enabled",      description: "AI-powered retrieval and generation. Learns from test history to improve coverage over time.",         grad: "from-pink-500 to-rose-500" },
    { icon: <GitBranch className="w-[22px] h-[22px]" />,     title: "CI/CD Compatible",         description: "Seamless GitHub, GitLab, and Jenkins integration. Plug into your existing pipeline in minutes.",       grad: "from-orange-500 to-amber-500" },
    { icon: <BarChart3 className="w-[22px] h-[22px]" />,     title: "Performance Monitoring",   description: "Track metrics, execution times, and coverage trends. Get actionable insights to ship faster.",         grad: "from-teal-500 to-emerald-500" },
    { icon: <Shield className="w-[22px] h-[22px]" />,        title: "Security Testing",         description: "Automated vulnerability scanning and compliance checks. Protect every release from threats.",           grad: "from-red-500 to-pink-500" },
    { icon: <Users className="w-[22px] h-[22px]" />,         title: "Multi-Team Support",       description: "Collaborate across QA, DevOps, and dev teams. Real-time dashboards, RBAC, and granular access.",      grad: "from-indigo-500 to-blue-500" },
  ];

  const trustItems = ["No credit card required", "5-minute setup", "Works with any web app"];

  return (
    <div className="min-h-screen" style={{ background: "#ffffff", color: "#111827", fontFamily: "-apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif", WebkitFontSmoothing: "antialiased" as any }}>

      {/* ── Global styles ── */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50%       { transform: translateY(-12px); }
        }
        html                      { overflow-y: scroll; }
        ::-webkit-scrollbar       { width: 8px; }
        ::-webkit-scrollbar-track { background: #f1f5f9; }
        ::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: #94a3b8; }
        ::selection               { background: rgba(99,102,241,0.2); color: #111827; }
      `}</style>

      {/* ── Subtle ambient tint (light) ── */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden" aria-hidden="true">
        <div className="absolute -top-40 -left-40 w-[600px] h-[600px] rounded-full"
          style={{ background: "radial-gradient(circle, rgba(99,102,241,0.06) 0%, transparent 70%)" }} />
        <div className="absolute top-0 right-0 w-[400px] h-[400px] rounded-full"
          style={{ background: "radial-gradient(circle, rgba(139,92,246,0.05) 0%, transparent 70%)" }} />
        <div className="absolute inset-0" style={{
          backgroundImage: "radial-gradient(circle, rgba(99,102,241,0.04) 1px, transparent 1px)",
          backgroundSize: "32px 32px",
        }} />
      </div>

      {/* ════════════════════════════════════════ */}
      {/* NAV                                     */}
      {/* ════════════════════════════════════════ */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 md:px-10 h-14"
        style={{ background: "rgba(255,255,255,0.92)", backdropFilter: "blur(16px)", borderBottom: "1px solid #e5e7eb" }}>
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg flex items-center justify-center"
            style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}>
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-base tracking-tight" style={{ color: "#111827" }}>ASTRA</span>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
            className="hidden sm:inline-flex text-sm font-medium px-4 py-1.5 rounded-lg transition-colors hover:bg-gray-50"
            style={{ color: "#374151", border: "1px solid #e5e7eb" }}
          >
            Sign In
          </button>
          <button
            onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
            className="text-sm font-semibold px-4 py-1.5 rounded-lg text-white transition-all hover:opacity-90"
            style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}
            data-testid="button-get-started"
          >
            Get Started
          </button>
        </div>
      </nav>

      {/* ════════════════════════════════════════ */}
      {/* HERO                                    */}
      {/* ════════════════════════════════════════ */}
      <section className="relative pt-28 md:pt-36 pb-20 px-6 overflow-hidden">

        {/* Badge pill */}
        <div className="flex justify-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold"
            style={{ background: "rgba(99,102,241,0.08)", border: "1px solid rgba(99,102,241,0.2)", color: "#4f46e5" }}>
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-pulse" />
            ✦ AI-Powered Autonomous Testing
          </div>
        </div>

        {/* 3-column layout */}
        <div className="max-w-[1200px] mx-auto flex items-center justify-center gap-8 xl:gap-12">

          {/* ── LEFT: metric cards ── */}
          <div className="hidden xl:flex flex-col gap-3 flex-shrink-0 w-52"
            style={{ animation: "float 6s ease-in-out 3s infinite" }}>

            {[
              { icon: <BarChart3 className="w-4 h-4" style={{ color: "#6366f1" }} />, bg: "rgba(99,102,241,0.08)", label: "Tests Generated", value: "2,847", sub: <span className="flex items-center gap-1 text-xs" style={{ color: "#059669" }}><TrendingUp className="w-3 h-3" />↑ 12% this week</span> },
              { icon: <CheckCircle2 className="w-4 h-4 text-emerald-500" />, bg: "rgba(16,185,129,0.08)", label: "Pass Rate", value: "98.4%", sub: <span className="text-xs" style={{ color: "#9ca3af" }}>across 1,240 runs</span> },
              { icon: <Users className="w-4 h-4 text-blue-500" />, bg: "rgba(59,130,246,0.08)", label: "Active Teams", value: "24", sub: <span className="text-xs" style={{ color: "#9ca3af" }}>across projects</span> },
            ].map((card, i) => (
              <div key={i} className="rounded-2xl p-4"
                style={{ background: "#ffffff", border: "1px solid #e5e7eb", boxShadow: "0 2px 12px rgba(0,0,0,0.06)" }}>
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: card.bg }}>
                    {card.icon}
                  </div>
                  <span className="text-xs font-medium" style={{ color: "#6b7280" }}>{card.label}</span>
                </div>
                <div className="text-2xl font-bold mb-1" style={{ color: "#111827" }}>{card.value}</div>
                {card.sub}
              </div>
            ))}
          </div>

          {/* ── CENTER: headline + CTA ── */}
          <div className="flex-1 flex flex-col items-center text-center min-w-0">

            <h1 className="mb-6" data-testid="heading-hero"
              style={{ fontSize: "clamp(2.5rem, 5.5vw, 4.5rem)", fontWeight: 800, letterSpacing: "-0.03em", lineHeight: 1.08, color: "#111827" }}>
              The Future of<br />
              Software{" "}
              <span style={{
                background: "linear-gradient(135deg, #6366f1, #8b5cf6, #06b6d4)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}>
                Testing
              </span>
            </h1>

            <p className="mb-8 max-w-[520px]" data-testid="text-subheading"
              style={{ color: "#6b7280", fontSize: "18px", lineHeight: 1.7 }}>
              ASTRA uses multi-agent AI to record, analyze, generate, and execute
              test cases autonomously — so your team can ship with confidence.
            </p>

            {/* CTA buttons */}
            <div className="flex flex-wrap items-center justify-center gap-4 mb-8">
              <button
                onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
                className="inline-flex items-center gap-2 font-semibold text-white rounded-[10px] transition-all duration-200 hover:opacity-90 hover:scale-[1.02]"
                style={{
                  background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                  padding: "14px 32px",
                  fontSize: "15px",
                  fontWeight: 600,
                  boxShadow: "0 4px 20px rgba(99,102,241,0.3)",
                }}
              >
                <Zap className="w-4 h-4" />
                Start Testing Free
              </button>
              <button
                onClick={() => document.getElementById("features-section")?.scrollIntoView({ behavior: "smooth" })}
                className="inline-flex items-center gap-2 font-semibold rounded-[10px] transition-all duration-200 hover:bg-gray-50"
                style={{
                  border: "1px solid #e5e7eb",
                  color: "#374151",
                  padding: "14px 32px",
                  fontSize: "15px",
                  fontWeight: 600,
                  background: "#ffffff",
                }}
              >
                Watch Demo
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Trust indicators with vertical bar separators */}
            <div className="flex flex-wrap items-center justify-center gap-x-3 gap-y-2">
              {trustItems.map((item, i) => (
                <span key={i} className="flex items-center gap-3">
                  <span className="flex items-center gap-1.5 text-xs" style={{ color: "#9ca3af" }}>
                    <CheckCircle2 className="w-3.5 h-3.5" style={{ color: "#6366f1" }} />
                    {item}
                  </span>
                  {i < trustItems.length - 1 && (
                    <span style={{ color: "#d1d5db", fontSize: "14px" }}>|</span>
                  )}
                </span>
              ))}
            </div>
          </div>

          {/* ── RIGHT: floating code card ── */}
          <div className="hidden xl:block flex-shrink-0 w-[320px]"
            style={{ animation: "float 6s ease-in-out infinite" }}>
            <div className="rounded-2xl overflow-hidden"
              style={{
                background: "#f8fafc",
                border: "1px solid #e2e8f0",
                boxShadow: "0 20px 50px rgba(0,0,0,0.08)",
              }}>
              {/* Window chrome */}
              <div className="flex items-center justify-between px-4 py-2.5"
                style={{ background: "#f1f5f9", borderBottom: "1px solid #e2e8f0" }}>
                <div className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                  <div className="w-2.5 h-2.5 rounded-full bg-yellow-400" />
                  <div className="w-2.5 h-2.5 rounded-full bg-green-400" />
                  <span className="ml-2 text-xs" style={{ color: "#94a3b8" }}>generated.spec.ts</span>
                </div>
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold"
                  style={{ background: "rgba(99,102,241,0.1)", color: "#6366f1", border: "1px solid rgba(99,102,241,0.2)" }}>
                  <Sparkles className="w-2.5 h-2.5" />
                  AI Generated
                </span>
              </div>
              {/* Code */}
              <div className="p-4 font-mono text-[12px] leading-[1.65]" style={{ background: "#f8fafc" }}>
                {CODE_LINES.map((line, li) => (
                  <div key={li} style={{ paddingLeft: `${line.indent * 16}px` }}>
                    {line.tokens.map((tok, ti) => (
                      <span key={ti} style={{ color: tok.color }}>{tok.text}</span>
                    ))}
                  </div>
                ))}
                <div className="mt-2 flex items-center gap-2">
                  <div className="w-1.5 h-[14px] rounded-sm animate-pulse" style={{ background: "#6366f1" }} />
                  <span style={{ color: "#9ca3af", fontSize: "10px" }}>Generating assertions…</span>
                </div>
              </div>
              {/* Status bar */}
              <div className="flex items-center justify-between px-4 py-2"
                style={{ background: "rgba(99,102,241,0.06)", borderTop: "1px solid rgba(99,102,241,0.12)" }}>
                <span className="text-[11px] font-semibold" style={{ color: "#6366f1" }}>✓ 7 assertions generated</span>
                <span className="text-[11px]" style={{ color: "#9ca3af" }}>0 failures</span>
              </div>
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="flex flex-col items-center gap-1.5 mt-16 opacity-30">
          <div className="w-px h-6 bg-gradient-to-b from-transparent via-indigo-400 to-transparent animate-pulse" />
          <div className="w-1 h-1 rounded-full bg-indigo-400" />
        </div>
      </section>

      {/* ════════════════════════════════════════ */}
      {/* FEATURES                                */}
      {/* ════════════════════════════════════════ */}
      <section id="features-section" className="relative px-6 py-24"
        style={{ background: "#f8fafc", borderTop: "1px solid #f1f5f9" }}>
        <div className="max-w-[1200px] mx-auto">

          <div className="text-center mb-14">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold mb-5"
              style={{ background: "rgba(99,102,241,0.08)", border: "1px solid rgba(99,102,241,0.15)", color: "#6366f1" }}>
              <Sparkles className="w-3 h-3" />
              Platform Capabilities
            </div>
            <h2 className="mb-3" data-testid="heading-features"
              style={{ fontSize: "40px", fontWeight: 700, color: "#111827", letterSpacing: "-0.02em" }}>
              Everything your QA team needs
            </h2>
            <p data-testid="text-features-subtitle"
              style={{ fontSize: "16px", color: "#6b7280" }}>
              One platform. Every testing capability.
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((feature, index) => (
              <div
                key={index}
                data-testid={`card-feature-${index}`}
                className="cursor-pointer transition-all duration-200"
                style={{
                  background: "#ffffff",
                  border: "1px solid #e5e7eb",
                  borderRadius: "16px",
                  padding: "28px",
                  boxShadow: "0 1px 4px rgba(0,0,0,0.04)",
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.border = "1px solid rgba(99,102,241,0.35)";
                  el.style.boxShadow = "0 4px 20px rgba(99,102,241,0.1)";
                  el.style.transform = "translateY(-2px)";
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.border = "1px solid #e5e7eb";
                  el.style.boxShadow = "0 1px 4px rgba(0,0,0,0.04)";
                  el.style.transform = "translateY(0)";
                }}
              >
                <div className={`w-11 h-11 rounded-xl flex items-center justify-center mb-4 bg-gradient-to-br ${feature.grad} text-white`}>
                  {feature.icon}
                </div>
                {/* Title: BLACK as requested */}
                <h3 className="mb-2" style={{ fontSize: "16px", fontWeight: 600, color: "#000000" }}>
                  {feature.title}
                </h3>
                <p style={{ fontSize: "14px", color: "#6b7280", lineHeight: 1.6 }}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════ */}
      {/* LOGIN / CHANGE-PASSWORD                 */}
      {/* ════════════════════════════════════════ */}
      <section id="login-section" className="relative px-6 py-20 pb-32"
        style={{ background: "#ffffff", borderTop: "1px solid #f1f5f9" }}>
        <div className="max-w-[420px] mx-auto">

          {mustChange ? (
            /* ── Change-password ── */
            <div className="rounded-[20px] p-10" data-testid="card-change-password"
              style={{ background: "#fff", border: "1px solid #fcd34d", boxShadow: "0 8px 40px rgba(0,0,0,0.08)" }}>
              <div className="space-y-5">
                <div className="text-center">
                  <div className="flex justify-center mb-4">
                    <div className="p-3 rounded-2xl" style={{ background: "rgba(245,158,11,0.08)" }}>
                      <ShieldCheck className="w-8 h-8 text-amber-500" />
                    </div>
                  </div>
                  <h2 style={{ fontSize: "26px", fontWeight: 700, color: "#111827" }}>Set Your Password</h2>
                  <p className="mt-2" style={{ fontSize: "14px", color: "#6b7280" }}>
                    You're using a temporary password. Please set a new one to continue.
                  </p>
                </div>

                <div className="flex items-start gap-3 p-3 rounded-xl"
                  style={{ background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.25)" }}>
                  <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0 mt-0.5" />
                  <p className="text-xs" style={{ color: "#92400e" }}>
                    Logged in as <strong>{email}</strong>. You must change your temporary password before continuing.
                  </p>
                </div>

                <form onSubmit={handleChangePassword} className="space-y-4">
                  <div>
                    <label className="block mb-1.5" style={{ fontSize: "13px", fontWeight: 500, color: "#374151" }}>
                      New Password
                    </label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                      <Input
                        type={showNewPw ? "text" : "password"}
                        placeholder="Min. 8 characters"
                        value={newPassword}
                        onChange={(e) => setNewPassword(e.target.value)}
                        className="pl-9 pr-10 border-gray-200 bg-gray-50 text-gray-900 placeholder:text-gray-400 focus:border-indigo-400 focus:ring-indigo-100"
                        autoFocus required
                        data-testid="input-new-password"
                      />
                      <button type="button" onClick={() => setShowNewPw(!showNewPw)} tabIndex={-1}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                        {showNewPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {newPassword.length > 0 && newPassword.length < 8 && (
                      <p className="mt-1 text-xs text-red-500">At least 8 characters required</p>
                    )}
                  </div>

                  <div>
                    <label className="block mb-1.5" style={{ fontSize: "13px", fontWeight: 500, color: "#374151" }}>
                      Confirm Password
                    </label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
                      <Input
                        type={showConfirmPw ? "text" : "password"}
                        placeholder="Confirm new password"
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                        className="pl-9 pr-10 border-gray-200 bg-gray-50 text-gray-900 placeholder:text-gray-400 focus:border-indigo-400 focus:ring-indigo-100"
                        required
                        data-testid="input-confirm-password"
                      />
                      <button type="button" onClick={() => setShowConfirmPw(!showConfirmPw)} tabIndex={-1}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                        {showConfirmPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {confirmPassword.length > 0 && newPassword !== confirmPassword && (
                      <p className="mt-1 text-xs text-red-500">Passwords do not match</p>
                    )}
                  </div>

                  <Button type="submit"
                    className="w-full font-semibold text-white"
                    style={{ background: "linear-gradient(135deg, #f59e0b, #d97706)", padding: "13px" }}
                    disabled={isChanging || newPassword.length < 8 || newPassword !== confirmPassword || newPassword === password}
                    data-testid="button-set-password">
                    {isChanging ? "Saving…" : "Set Password & Continue"}
                  </Button>
                </form>
              </div>
            </div>

          ) : (
            /* ── Normal login ── */
            <>
              <div className="text-center mb-8">
                <h2 data-testid="heading-login"
                  style={{ fontSize: "28px", fontWeight: 700, color: "#111827", letterSpacing: "-0.02em" }}>
                  Welcome back
                </h2>
                <p className="mt-2" data-testid="text-demo-mode"
                  style={{ fontSize: "15px", color: "#6b7280" }}>
                  Sign in to your ASTRA workspace
                </p>
              </div>

              <div className="rounded-[20px] p-10" data-testid="card-login"
                style={{ background: "#ffffff", border: "1px solid #e5e7eb", boxShadow: "0 8px 40px rgba(0,0,0,0.08)" }}>
                <form onSubmit={handleLogin} className="space-y-5">

                  {/* Email */}
                  <div>
                    <label className="block mb-1.5" style={{ fontSize: "13px", fontWeight: 500, color: "#374151" }}>
                      Email address
                    </label>
                    <Input
                      type="text"
                      placeholder="you@company.com"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="border-gray-200 bg-gray-50 text-gray-900 placeholder:text-gray-400 focus:border-indigo-400 focus:ring-indigo-100"
                      autoComplete="username"
                      required
                      data-testid="input-email"
                    />
                  </div>

                  {/* Password — with eye icon toggle */}
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <label style={{ fontSize: "13px", fontWeight: 500, color: "#374151" }}>
                        Password
                      </label>
                      <span className="text-[13px] cursor-default select-none" style={{ color: "#6366f1" }}>
                        Forgot password?
                      </span>
                    </div>
                    <div className="relative">
                      <Input
                        type={showPassword ? "text" : "password"}
                        placeholder="Enter your password"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="pr-10 border-gray-200 bg-gray-50 text-gray-900 placeholder:text-gray-400 focus:border-indigo-400 focus:ring-indigo-100"
                        autoComplete="current-password"
                        required
                        data-testid="input-password"
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        tabIndex={-1}
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600 transition-colors"
                        aria-label={showPassword ? "Hide password" : "Show password"}
                      >
                        {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                  </div>

                  <Button
                    type="submit"
                    className="w-full font-semibold text-white transition-all hover:opacity-90"
                    style={{
                      background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                      padding: "13px",
                      fontSize: "15px",
                      fontWeight: 600,
                      letterSpacing: "0.01em",
                      boxShadow: "0 4px 14px rgba(99,102,241,0.3)",
                    }}
                    disabled={isLoading}
                    data-testid="button-login"
                  >
                    {isLoading ? "Signing in…" : "Sign In →"}
                  </Button>
                </form>

                <div className="mt-6 pt-5" style={{ borderTop: "1px solid #f3f4f6" }}>
                  <p className="text-center" style={{ fontSize: "13px", color: "#9ca3af" }}>
                    Don't have an account?{" "}
                    <span style={{ color: "#6b7280" }}>Contact your admin</span>
                  </p>
                </div>
              </div>
            </>
          )}
        </div>
      </section>

      {/* ════════════════════════════════════════ */}
      {/* FOOTER                                  */}
      {/* ════════════════════════════════════════ */}
      <footer className="relative px-6 py-8"
        style={{ background: "#f8fafc", borderTop: "1px solid #e5e7eb" }}>
        <div className="max-w-[1200px] mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded-md flex items-center justify-center"
              style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}>
              <Sparkles className="w-3 h-3 text-white" />
            </div>
            <span className="text-sm font-bold" style={{ color: "#111827" }}>ASTRA</span>
            <span className="text-xs" style={{ color: "#9ca3af" }}>by Nousinfo Systems</span>
          </div>
          <p className="text-xs" style={{ color: "#9ca3af" }}>
            © {new Date().getFullYear()} Nousinfo Systems · AI-Powered Test Automation
          </p>
        </div>
      </footer>

    </div>
  );
}
