import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Bot, Eye, Settings, Accessibility, Code2, Brain,
  GitBranch, BarChart3, Shield, Users, Lock, ShieldCheck,
  AlertTriangle, EyeOff, Zap, ArrowRight, CheckCircle2,
  Sparkles, TrendingUp,
} from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { useBranding } from "@/contexts/BrandingContext";

/* ─────────────────────────────────────────────────────── */
/*  Syntax-highlighted code lines for the floating card   */
/* ─────────────────────────────────────────────────────── */
type CodeToken = { text: string; color: string };
type CodeLine  = { indent: number; tokens: CodeToken[] };

const CODE_LINES: CodeLine[] = [
  { indent: 0, tokens: [{ text: "// Generated by ASTRA AI", color: "#4b5563" }] },
  { indent: 0, tokens: [
    { text: "test", color: "#818cf8" },
    { text: "('User login flow', ", color: "#94a3b8" },
    { text: "async", color: "#818cf8" },
    { text: " ({ page }) => {", color: "#94a3b8" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#94a3b8" },
    { text: "page", color: "#60a5fa" },
    { text: ".goto(", color: "#94a3b8" },
    { text: "'/login'", color: "#34d399" },
    { text: ")", color: "#94a3b8" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#94a3b8" },
    { text: "page", color: "#60a5fa" },
    { text: ".fill(", color: "#94a3b8" },
    { text: "'#email'", color: "#34d399" },
    { text: ", user.email)", color: "#94a3b8" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#94a3b8" },
    { text: "page", color: "#60a5fa" },
    { text: ".fill(", color: "#94a3b8" },
    { text: "'#password'", color: "#34d399" },
    { text: ", user.password)", color: "#94a3b8" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#94a3b8" },
    { text: "page", color: "#60a5fa" },
    { text: ".click(", color: "#94a3b8" },
    { text: "'button[type=\"submit\"]'", color: "#34d399" },
    { text: ")", color: "#94a3b8" },
  ]},
  { indent: 1, tokens: [
    { text: "await ", color: "#94a3b8" },
    { text: "expect", color: "#f472b6" },
    { text: "(page).toHaveURL(", color: "#94a3b8" },
    { text: "'/dashboard'", color: "#34d399" },
    { text: ")", color: "#94a3b8" },
  ]},
  { indent: 0, tokens: [{ text: "})", color: "#94a3b8" }] },
];

/* ─────────────────────────────────────────────────────── */
export default function LandingPage() {
  const [, setLocation] = useLocation();

  /* ── All state is UNTOUCHED ── */
  const [email, setEmail]           = useState("");
  const [password, setPassword]     = useState("");
  const [isLoading, setIsLoading]   = useState(false);
  const { toast }  = useToast();
  const { brand }  = useBranding();

  const [mustChange,     setMustChange]     = useState(false);
  const [newPassword,    setNewPassword]    = useState("");
  const [confirmPassword,setConfirmPassword]= useState("");
  const [showNewPw,      setShowNewPw]      = useState(false);
  const [showConfirmPw,  setShowConfirmPw]  = useState(false);
  const [isChanging,     setIsChanging]     = useState(false);

  /* ── Auth redirect (UNTOUCHED) ── */
  useEffect(() => {
    const isAuthenticated = localStorage.getItem("isAuthenticated") === "true";
    if (isAuthenticated) setLocation("/dashboard");
  }, [setLocation]);

  /* ── Login handler (UNTOUCHED) ── */
  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      const res  = await fetch("/api/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username: email.trim(), password }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        localStorage.setItem("isAuthenticated", "true");
        localStorage.setItem("currentUser", JSON.stringify({
          id: data.userId, username: data.username, tenantId: data.tenantId,
        }));
        if (data.mustChangePassword) {
          setMustChange(true);
        } else {
          setLocation("/dashboard");
        }
      } else {
        toast({ variant: "destructive", title: "Login failed", description: data.error || "Invalid credentials" });
      }
    } catch (error: any) {
      toast({ variant: "destructive", title: "Login failed", description: error.message || "Please try again" });
    } finally {
      setIsLoading(false);
    }
  };

  /* ── Change-password handler (UNTOUCHED) ── */
  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newPassword.length < 8) {
      toast({ title: "Too short", description: "Password must be at least 8 characters", variant: "destructive" });
      return;
    }
    if (newPassword !== confirmPassword) {
      toast({ title: "Mismatch", description: "Passwords do not match", variant: "destructive" });
      return;
    }
    if (newPassword === password) {
      toast({ title: "Same password", description: "New password must be different from the temporary one", variant: "destructive" });
      return;
    }
    setIsChanging(true);
    try {
      const res  = await fetch("/api/auth/change-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ currentPassword: password, newPassword }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        toast({ title: "Password updated", description: "Your new password is set. Welcome!" });
        setLocation("/dashboard");
      } else {
        toast({ title: "Failed", description: data.error || "Could not update password", variant: "destructive" });
      }
    } catch {
      toast({ title: "Network error", description: "Could not reach the server", variant: "destructive" });
    } finally {
      setIsChanging(false);
    }
  };

  /* ── Feature data ── */
  const features = [
    { icon: <Bot className="w-[22px] h-[22px]" />,         title: "AI Agent Testing",         description: "Autonomous agents analyze your apps and generate comprehensive test cases — no scripts needed.",      grad: "from-indigo-500 to-violet-500" },
    { icon: <Eye className="w-[22px] h-[22px]" />,          title: "Visual Regression",         description: "Compare Figma designs with live websites. Detect layout, color, and spacing discrepancies instantly.", grad: "from-violet-500 to-purple-500" },
    { icon: <Settings className="w-[22px] h-[22px]" />,     title: "Functional Testing",        description: "Test clicks, form submissions, navigation flows, and user interactions end-to-end, automatically.",   grad: "from-blue-500 to-indigo-500" },
    { icon: <Accessibility className="w-[22px] h-[22px]" />,title: "Accessibility Compliance",  description: "Automated WCAG AA compliance testing. Catch contrast issues, keyboard nav, and screen reader gaps.",   grad: "from-cyan-500 to-blue-500" },
    { icon: <Code2 className="w-[22px] h-[22px]" />,        title: "Code Review & QA",          description: "Intelligent code analysis with automated quality checks. Review PRs and surface issues early.",         grad: "from-emerald-500 to-cyan-500" },
    { icon: <Brain className="w-[22px] h-[22px]" />,        title: "Agentic RAG Enabled",       description: "AI-powered retrieval and generation. Learns from test history to improve coverage over time.",         grad: "from-pink-500 to-rose-500" },
    { icon: <GitBranch className="w-[22px] h-[22px]" />,    title: "CI/CD Compatible",          description: "Seamless GitHub, GitLab, and Jenkins integration. Plug into your existing pipeline in minutes.",       grad: "from-orange-500 to-amber-500" },
    { icon: <BarChart3 className="w-[22px] h-[22px]" />,    title: "Performance Monitoring",    description: "Track metrics, execution times, and coverage trends. Get actionable insights to ship faster.",         grad: "from-teal-500 to-emerald-500" },
    { icon: <Shield className="w-[22px] h-[22px]" />,       title: "Security Testing",          description: "Automated vulnerability scanning and compliance checks. Protect every release from threats.",           grad: "from-red-500 to-pink-500" },
    { icon: <Users className="w-[22px] h-[22px]" />,        title: "Multi-Team Support",        description: "Collaborate across QA, DevOps, and dev teams. Real-time dashboards, RBAC, and granular access.",      grad: "from-indigo-500 to-blue-500" },
  ];

  /* ── Shared input style for login form ── */
  const inputStyle: React.CSSProperties = {
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "10px",
    color: "#ffffff",
    padding: "13px 16px",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    transition: "border-color 0.2s, box-shadow 0.2s",
  };

  /* ─────────────────────────────────────────────────── */
  return (
    <div className="min-h-screen" style={{ background: "#0A0A0F", color: "#ffffff", fontFamily: "-apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', sans-serif", WebkitFontSmoothing: "antialiased" as any }}>

      {/* ── Global keyframes & scrollbar ── */}
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50%       { transform: translateY(-12px); }
        }
        @keyframes float-delayed {
          0%, 100% { transform: translateY(0px); }
          50%       { transform: translateY(-8px); }
        }
        ::-webkit-scrollbar       { width: 6px; }
        ::-webkit-scrollbar-track { background: #0A0A0F; }
        ::-webkit-scrollbar-thumb { background: #334155; border-radius: 3px; }
        ::selection               { background: rgba(99,102,241,0.3); color: #ffffff; }
        .login-input:focus        { border-color: #6366f1 !important; box-shadow: 0 0 0 3px rgba(99,102,241,0.15) !important; }
      `}</style>

      {/* ── Ambient background glows (fixed) ── */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden" aria-hidden="true">
        <div className="absolute -top-40 -left-40 w-[700px] h-[700px] rounded-full"
          style={{ background: "radial-gradient(circle, rgba(99,102,241,0.15) 0%, transparent 70%)" }} />
        <div className="absolute -top-20 right-0 w-[500px] h-[500px] rounded-full"
          style={{ background: "radial-gradient(circle, rgba(139,92,246,0.10) 0%, transparent 70%)" }} />
        <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] rounded-full"
          style={{ background: "radial-gradient(circle, rgba(59,130,246,0.08) 0%, transparent 70%)" }} />
        <div className="absolute inset-0" style={{
          backgroundImage: "radial-gradient(circle, rgba(255,255,255,0.06) 1px, transparent 1px)",
          backgroundSize: "32px 32px",
        }} />
      </div>

      {/* ════════════════════════════════════════════════ */}
      {/* NAV                                             */}
      {/* ════════════════════════════════════════════════ */}
      <nav className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-6 md:px-10 h-14"
        style={{
          background: "rgba(10,10,15,0.85)",
          backdropFilter: "blur(16px)",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
        }}>
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 rounded-lg flex items-center justify-center"
            style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}>
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-base tracking-tight text-white">ASTRA</span>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
            className="hidden sm:inline-flex text-sm font-medium px-4 py-1.5 rounded-lg transition-colors hover:bg-white/5"
            style={{ color: "#94a3b8", border: "1px solid rgba(255,255,255,0.1)" }}
          >
            Sign In
          </button>
          <button
            onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
            className="text-sm font-semibold px-4 py-1.5 rounded-lg text-white transition-all hover:opacity-90 hover:scale-[1.02]"
            style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}
            data-testid="button-get-started"
          >
            Get Started
          </button>
        </div>
      </nav>

      {/* ════════════════════════════════════════════════ */}
      {/* HERO                                            */}
      {/* ════════════════════════════════════════════════ */}
      <section className="relative pt-28 md:pt-36 pb-20 px-6 overflow-hidden">

        {/* Badge pill — centered above everything */}
        <div className="flex justify-center mb-10">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-semibold"
            style={{ background: "rgba(99,102,241,0.15)", border: "1px solid rgba(99,102,241,0.3)", color: "#a5b4fc" }}>
            <span className="w-1.5 h-1.5 rounded-full bg-indigo-400 animate-pulse" />
            ✦ AI-Powered Autonomous Testing
          </div>
        </div>

        {/* 3-column layout: [metrics] [text] [code] */}
        <div className="max-w-[1200px] mx-auto flex items-center justify-center gap-8 xl:gap-12">

          {/* ── LEFT: metrics card (desktop only) ── */}
          <div className="hidden xl:flex flex-col gap-3 flex-shrink-0 w-52"
            style={{ animation: "float 6s ease-in-out 3s infinite" }}>

            {/* Tests generated */}
            <div className="rounded-2xl p-4"
              style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", backdropFilter: "blur(12px)" }}>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: "rgba(99,102,241,0.15)" }}>
                  <BarChart3 className="w-4 h-4" style={{ color: "#818cf8" }} />
                </div>
                <span className="text-xs font-medium" style={{ color: "#64748b" }}>Tests Generated</span>
              </div>
              <div className="text-2xl font-bold text-white mb-1">2,847</div>
              <div className="flex items-center gap-1">
                <TrendingUp className="w-3 h-3 text-emerald-400" />
                <span className="text-xs text-emerald-400 font-medium">↑ 12% this week</span>
              </div>
            </div>

            {/* Pass rate */}
            <div className="rounded-2xl p-4"
              style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", backdropFilter: "blur(12px)" }}>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: "rgba(16,185,129,0.15)" }}>
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                </div>
                <span className="text-xs font-medium" style={{ color: "#64748b" }}>Pass Rate</span>
              </div>
              <div className="text-2xl font-bold text-white mb-1">98.4%</div>
              <div className="text-xs" style={{ color: "#475569" }}>across 1,240 runs</div>
            </div>

            {/* Teams */}
            <div className="rounded-2xl p-4"
              style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", backdropFilter: "blur(12px)" }}>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: "rgba(59,130,246,0.15)" }}>
                  <Users className="w-4 h-4 text-blue-400" />
                </div>
                <span className="text-xs font-medium" style={{ color: "#64748b" }}>Active Teams</span>
              </div>
              <div className="text-2xl font-bold text-white">24</div>
            </div>
          </div>

          {/* ── CENTER: headline + CTA ── */}
          <div className="flex-1 flex flex-col items-center text-center min-w-0">

            <h1 className="mb-6" data-testid="heading-hero"
              style={{ fontSize: "clamp(2.5rem, 5.5vw, 4.5rem)", fontWeight: 800, letterSpacing: "-0.03em", lineHeight: 1.08, color: "#ffffff" }}>
              The Future of<br />
              Software{" "}
              <span style={{
                background: "linear-gradient(135deg, #6366f1, #8b5cf6, #06b6d4)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
              }}>
                Testing
              </span>
            </h1>

            <p className="mb-8 max-w-[520px]" data-testid="text-subheading"
              style={{ color: "#94a3b8", fontSize: "18px", lineHeight: 1.7 }}>
              ASTRA uses multi-agent AI to record, analyze, generate, and execute
              test cases autonomously — so your team can ship with confidence.
            </p>

            {/* CTA buttons */}
            <div className="flex flex-wrap items-center justify-center gap-4 mb-8">
              <button
                onClick={() => document.getElementById("login-section")?.scrollIntoView({ behavior: "smooth" })}
                className="inline-flex items-center gap-2 font-semibold text-white rounded-[10px] transition-all duration-200 hover:scale-[1.02]"
                style={{
                  background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                  padding: "14px 32px",
                  fontSize: "15px",
                  fontWeight: 600,
                  boxShadow: "0 0 40px rgba(99,102,241,0.3)",
                }}
              >
                <Zap className="w-4 h-4" />
                Start Testing Free
              </button>
              <button
                onClick={() => document.getElementById("features-section")?.scrollIntoView({ behavior: "smooth" })}
                className="inline-flex items-center gap-2 font-semibold rounded-[10px] transition-all duration-200 hover:bg-white/5"
                style={{
                  border: "1px solid rgba(255,255,255,0.15)",
                  color: "#ffffff",
                  padding: "14px 32px",
                  fontSize: "15px",
                  fontWeight: 600,
                  background: "transparent",
                }}
              >
                Watch Demo
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            {/* Trust indicators */}
            <div className="flex flex-wrap items-center justify-center gap-x-5 gap-y-2">
              {["No credit card required", "5-minute setup", "Works with any web app"].map((item, i, arr) => (
                <span key={i} className="flex items-center gap-1.5">
                  <span className="flex items-center gap-1.5 text-xs" style={{ color: "#64748b" }}>
                    <CheckCircle2 className="w-3.5 h-3.5" style={{ color: "#6366f1" }} />
                    {item}
                  </span>
                  {i < arr.length - 1 && (
                    <span className="text-xs" style={{ color: "#1e293b" }}>·</span>
                  )}
                </span>
              ))}
            </div>
          </div>

          {/* ── RIGHT: floating code card (desktop only) ── */}
          <div className="hidden xl:block flex-shrink-0 w-[320px]"
            style={{ animation: "float 6s ease-in-out infinite" }}>

            <div className="rounded-2xl overflow-hidden"
              style={{
                background: "#0d1117",
                border: "1px solid rgba(255,255,255,0.08)",
                boxShadow: "0 24px 60px rgba(0,0,0,0.5)",
              }}>
              {/* Window chrome */}
              <div className="flex items-center justify-between px-4 py-2.5"
                style={{ background: "rgba(255,255,255,0.03)", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
                <div className="flex items-center gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ background: "#ef4444", opacity: 0.7 }} />
                  <div className="w-2.5 h-2.5 rounded-full" style={{ background: "#f59e0b", opacity: 0.7 }} />
                  <div className="w-2.5 h-2.5 rounded-full" style={{ background: "#10b981", opacity: 0.7 }} />
                  <span className="ml-2 text-xs" style={{ color: "#475569" }}>generated.spec.ts</span>
                </div>
                {/* AI Generated badge */}
                <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold"
                  style={{ background: "rgba(99,102,241,0.15)", color: "#818cf8", border: "1px solid rgba(99,102,241,0.25)" }}>
                  <Sparkles className="w-2.5 h-2.5" />
                  AI Generated
                </span>
              </div>

              {/* Code body */}
              <div className="p-4 font-mono text-[12px] leading-[1.65]">
                {CODE_LINES.map((line, li) => (
                  <div key={li} style={{ paddingLeft: `${line.indent * 16}px` }}>
                    {line.tokens.map((tok, ti) => (
                      <span key={ti} style={{ color: tok.color }}>{tok.text}</span>
                    ))}
                  </div>
                ))}
                {/* Cursor */}
                <div className="mt-2 flex items-center gap-2">
                  <div className="w-1.5 h-[14px] rounded-sm animate-pulse" style={{ background: "#6366f1" }} />
                  <span style={{ color: "#334155", fontSize: "10px" }}>Generating assertions…</span>
                </div>
              </div>

              {/* Status bar */}
              <div className="flex items-center justify-between px-4 py-2"
                style={{ background: "rgba(99,102,241,0.08)", borderTop: "1px solid rgba(99,102,241,0.15)" }}>
                <span className="text-[11px] font-semibold" style={{ color: "#818cf8" }}>✓ 7 assertions generated</span>
                <span className="text-[11px]" style={{ color: "#475569" }}>0 failures</span>
              </div>
            </div>
          </div>
        </div>

        {/* Scroll indicator */}
        <div className="flex flex-col items-center gap-1.5 mt-16 opacity-30">
          <div className="w-px h-6 bg-gradient-to-b from-transparent via-indigo-500 to-transparent animate-pulse" />
          <div className="w-1 h-1 rounded-full bg-indigo-400" />
        </div>
      </section>

      {/* ════════════════════════════════════════════════ */}
      {/* FEATURES                                        */}
      {/* ════════════════════════════════════════════════ */}
      <section id="features-section" className="relative px-6 py-24"
        style={{ borderTop: "1px solid rgba(255,255,255,0.04)" }}>
        <div className="max-w-[1200px] mx-auto">

          {/* Section heading */}
          <div className="text-center mb-14">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-semibold mb-5"
              style={{ background: "rgba(99,102,241,0.1)", border: "1px solid rgba(99,102,241,0.2)", color: "#818cf8" }}>
              <Sparkles className="w-3 h-3" />
              Platform Capabilities
            </div>
            <h2 className="mb-3" data-testid="heading-features"
              style={{ fontSize: "40px", fontWeight: 700, color: "#ffffff", letterSpacing: "-0.02em" }}>
              Everything your QA team needs
            </h2>
            <p data-testid="text-features-subtitle"
              style={{ fontSize: "16px", color: "#64748b" }}>
              One platform. Every testing capability.
            </p>
          </div>

          {/* 3-column grid */}
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((feature, index) => (
              <div
                key={index}
                data-testid={`card-feature-${index}`}
                className="group relative cursor-pointer transition-all duration-200"
                style={{
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: "16px",
                  padding: "28px",
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.border = "1px solid rgba(99,102,241,0.4)";
                  el.style.background = "rgba(99,102,241,0.05)";
                  el.style.transform = "translateY(-2px)";
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget as HTMLElement;
                  el.style.border = "1px solid rgba(255,255,255,0.07)";
                  el.style.background = "rgba(255,255,255,0.03)";
                  el.style.transform = "translateY(0)";
                }}
              >
                {/* Icon */}
                <div className={`w-11 h-11 rounded-xl flex items-center justify-center mb-4 bg-gradient-to-br ${feature.grad} text-white`}
                  style={{ opacity: 0.9 }}>
                  {feature.icon}
                </div>
                <h3 className="mb-2" style={{ fontSize: "16px", fontWeight: 600, color: "#ffffff" }}>
                  {feature.title}
                </h3>
                <p style={{ fontSize: "14px", color: "#94a3b8", lineHeight: 1.6 }}>
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ════════════════════════════════════════════════ */}
      {/* LOGIN / CHANGE-PASSWORD                         */}
      {/* ════════════════════════════════════════════════ */}
      <section id="login-section" className="relative px-6 py-20 pb-32"
        style={{ background: "#0d0d14", borderTop: "1px solid rgba(255,255,255,0.06)" }}>
        <div className="max-w-[420px] mx-auto">

          {/* ── Change-password state ── */}
          {mustChange ? (
            <div className="rounded-[20px] p-12" data-testid="card-change-password"
              style={{
                background: "rgba(255,255,255,0.04)",
                border: "1px solid rgba(245,158,11,0.25)",
                backdropFilter: "blur(20px)",
                boxShadow: "0 25px 50px rgba(0,0,0,0.5)",
              }}>
              <div className="space-y-6">
                <div className="text-center">
                  <div className="flex justify-center mb-4">
                    <div className="p-3 rounded-2xl" style={{ background: "rgba(245,158,11,0.1)" }}>
                      <ShieldCheck className="w-8 h-8 text-amber-400" />
                    </div>
                  </div>
                  <h2 style={{ fontSize: "28px", fontWeight: 700, color: "#ffffff" }}>Set Your Password</h2>
                  <p className="mt-2" style={{ fontSize: "15px", color: "#64748b" }}>
                    You're using a temporary password. Please set a new one to continue.
                  </p>
                </div>

                <div className="flex items-start gap-3 p-3 rounded-xl"
                  style={{ background: "rgba(245,158,11,0.08)", border: "1px solid rgba(245,158,11,0.2)" }}>
                  <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                  <p className="text-xs text-amber-300">
                    Logged in as <strong>{email}</strong>. You must change your temporary password before continuing.
                  </p>
                </div>

                <form onSubmit={handleChangePassword} className="space-y-4">
                  <div>
                    <label className="block mb-1.5 text-xs font-medium" style={{ color: "#94a3b8" }}>
                      New Password
                    </label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{ color: "#475569" }} />
                      <Input
                        type={showNewPw ? "text" : "password"}
                        placeholder="Min. 8 characters"
                        value={newPassword}
                        onChange={(e) => setNewPassword(e.target.value)}
                        className="login-input pl-9 pr-10 bg-white/5 border-white/10 text-white placeholder:text-slate-600"
                        style={inputStyle}
                        autoFocus
                        required
                        data-testid="input-new-password"
                      />
                      <button type="button" onClick={() => setShowNewPw(!showNewPw)}
                        className="absolute right-3 top-1/2 -translate-y-1/2" style={{ color: "#475569" }} tabIndex={-1}>
                        {showNewPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {newPassword.length > 0 && newPassword.length < 8 && (
                      <p className="mt-1 text-xs text-red-400">At least 8 characters required</p>
                    )}
                  </div>

                  <div>
                    <label className="block mb-1.5 text-xs font-medium" style={{ color: "#94a3b8" }}>
                      Confirm Password
                    </label>
                    <div className="relative">
                      <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4" style={{ color: "#475569" }} />
                      <Input
                        type={showConfirmPw ? "text" : "password"}
                        placeholder="Confirm new password"
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                        className="login-input pl-9 pr-10 bg-white/5 border-white/10 text-white placeholder:text-slate-600"
                        style={inputStyle}
                        required
                        data-testid="input-confirm-password"
                      />
                      <button type="button" onClick={() => setShowConfirmPw(!showConfirmPw)}
                        className="absolute right-3 top-1/2 -translate-y-1/2" style={{ color: "#475569" }} tabIndex={-1}>
                        {showConfirmPw ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      </button>
                    </div>
                    {confirmPassword.length > 0 && newPassword !== confirmPassword && (
                      <p className="mt-1 text-xs text-red-400">Passwords do not match</p>
                    )}
                  </div>

                  <Button
                    type="submit"
                    className="w-full font-semibold text-white mt-2"
                    style={{ background: "linear-gradient(135deg, #f59e0b, #d97706)", padding: "14px", letterSpacing: "0.02em" }}
                    disabled={isChanging || newPassword.length < 8 || newPassword !== confirmPassword || newPassword === password}
                    data-testid="button-set-password"
                  >
                    {isChanging ? "Saving…" : "Set Password & Continue"}
                  </Button>
                </form>
              </div>
            </div>

          ) : (
            /* ── Normal login state ── */
            <>
              {/* Heading above card */}
              <div className="text-center mb-8">
                <h2 data-testid="heading-login"
                  style={{ fontSize: "28px", fontWeight: 700, color: "#ffffff", letterSpacing: "-0.02em" }}>
                  Welcome back
                </h2>
                <p className="mt-2" data-testid="text-demo-mode"
                  style={{ fontSize: "15px", color: "#64748b" }}>
                  Sign in to your ASTRA workspace
                </p>
              </div>

              {/* Glassmorphism login card */}
              <div className="rounded-[20px] p-12" data-testid="card-login"
                style={{
                  background: "rgba(255,255,255,0.04)",
                  border: "1px solid rgba(255,255,255,0.1)",
                  backdropFilter: "blur(20px)",
                  boxShadow: "0 25px 50px rgba(0,0,0,0.5)",
                }}>
                <form onSubmit={handleLogin} className="space-y-5">

                  {/* Email */}
                  <div>
                    <label className="block mb-1.5" style={{ fontSize: "13px", fontWeight: 500, color: "#94a3b8" }}>
                      Email address
                    </label>
                    <Input
                      type="text"
                      placeholder="you@company.com"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      className="login-input bg-white/5 border-white/10 text-white placeholder:text-slate-600"
                      style={inputStyle}
                      autoComplete="username"
                      required
                      data-testid="input-email"
                    />
                  </div>

                  {/* Password */}
                  <div>
                    <div className="flex items-center justify-between mb-1.5">
                      <label style={{ fontSize: "13px", fontWeight: 500, color: "#94a3b8" }}>
                        Password
                      </label>
                      <span className="text-[13px] cursor-default" style={{ color: "#6366f1" }}>
                        Forgot password?
                      </span>
                    </div>
                    <Input
                      type="password"
                      placeholder="Enter your password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      className="login-input bg-white/5 border-white/10 text-white placeholder:text-slate-600"
                      style={inputStyle}
                      autoComplete="current-password"
                      required
                      data-testid="input-password"
                    />
                  </div>

                  {/* Submit */}
                  <Button
                    type="submit"
                    className="w-full font-semibold text-white transition-all hover:opacity-90 mt-1"
                    style={{
                      background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                      padding: "14px",
                      fontSize: "15px",
                      fontWeight: 600,
                      letterSpacing: "0.02em",
                      boxShadow: "0 0 30px rgba(99,102,241,0.25)",
                    }}
                    disabled={isLoading}
                    data-testid="button-login"
                  >
                    {isLoading ? "Signing in…" : "Sign In →"}
                  </Button>
                </form>

                {/* Divider */}
                <div className="mt-6 pt-5" style={{ borderTop: "1px solid rgba(255,255,255,0.06)" }}>
                  <p className="text-center" style={{ fontSize: "13px", color: "#475569" }}>
                    Don't have an account?{" "}
                    <span style={{ color: "#64748b" }}>Contact your admin</span>
                  </p>
                </div>
              </div>
            </>
          )}
        </div>
      </section>

      {/* ════════════════════════════════════════════════ */}
      {/* FOOTER                                          */}
      {/* ════════════════════════════════════════════════ */}
      <footer className="relative px-6 py-8"
        style={{ background: "#0d0d14", borderTop: "1px solid rgba(255,255,255,0.05)" }}>
        <div className="max-w-[1200px] mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded-md flex items-center justify-center"
              style={{ background: "linear-gradient(135deg, #6366f1, #8b5cf6)" }}>
              <Sparkles className="w-3 h-3 text-white" />
            </div>
            <span className="text-sm font-bold text-white">ASTRA</span>
            <span className="text-xs" style={{ color: "#334155" }}>by Nousinfo Systems</span>
          </div>
          <p className="text-xs" style={{ color: "#334155" }}>
            © {new Date().getFullYear()} Nousinfo Systems · AI-Powered Test Automation
          </p>
        </div>
      </footer>

    </div>
  );
}
