import { Page } from '@playwright/test';

/**
 * Page Object: Find an Agency - Amerisure
 * URL: https://amerisure.com/agency/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class AgencyPage {
  constructor(readonly page: Page) {}

  readonly search_as_i_move_the_mapField = this.page.locator('input:nth-of-type(1)').first();
  readonly geolocationField = this.page.locator('[placeholder="Enter City, State, or Zip"]').first();
  readonly show_results_within_miField = this.page.locator('input:nth-of-type(3)').first();
  readonly search_contentField = this.page.locator('[name="search_results_2"]').first();
  readonly search_forField = this.page.locator('[name="s"]').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();

  async fillSearchAsIMoveTheMap(value = 'Test Value'): Promise<void> {
    await this.search_as_i_move_the_mapField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_as_i_move_the_mapField.fill('');
    await this.search_as_i_move_the_mapField.fill(value);
  }

  async fillGeolocation(value = 'Test Value'): Promise<void> {
    await this.geolocationField.waitFor({ state: 'visible', timeout: 8000 });
    await this.geolocationField.fill('');
    await this.geolocationField.fill(value);
  }

  async fillShowResultsWithinMi(value = '25'): Promise<void> {
    await this.show_results_within_miField.waitFor({ state: 'visible', timeout: 8000 });
    await this.show_results_within_miField.fill('');
    await this.show_results_within_miField.fill(value);
  }

  async fillSearchContent(value = 'Test Value'): Promise<void> {
    await this.search_contentField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_contentField.fill('');
    await this.search_contentField.fill(value);
  }

  async fillSearchFor(value = 'Test Value'): Promise<void> {
    await this.search_forField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_forField.fill('');
    await this.search_forField.fill(value);
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickNavFindAnAgency(): Promise<void> {
    await this.page.getByRole('link', { name: 'Find an Agency' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavPayMyBill(): Promise<void> {
    await this.page.getByRole('link', { name: 'Pay My Bill' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavForPolicyholders(): Promise<void> {
    await this.page.getByRole('link', { name: 'For Policyholders' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavFileAClaim(): Promise<void> {
    await this.page.getByRole('link', { name: 'File a Claim' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavReportPayroll(): Promise<void> {
    await this.page.getByRole('link', { name: 'Report Payroll' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavLocateAProvider(): Promise<void> {
    await this.page.getByRole('link', { name: 'Locate a Provider' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/agency/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
