import { Page } from '@playwright/test';

/**
 * Page Object: Careers - Amerisure
 * URL: https://amerisure.com/careers/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class CareersPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly search_forField = this.page.locator('[name="s"]').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly professional_development_btn = this.page.locator('button:has-text("Professional Development")').first();
  readonly diversity_equity_and_inclusion_btn = this.page.locator('button:has-text("Diversity, Equity and Inclusion")').first();
  readonly employee_recognition_btn = this.page.locator('button:has-text("Employee Recognition")').first();
  readonly early_career_btn = this.page.locator('button:has-text("Early Career")').first();
  readonly experienced_professionals_btn = this.page.locator('button:has-text("Experienced Professionals")').first();
  readonly total_rewards_btn = this.page.locator('button:has-text("Total Rewards")').first();

  async verifyHeading(expected = 'Amerisure Careers'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearchFor(value = 'Test Value'): Promise<void> {
    await this.search_forField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_forField.fill('');
    await this.search_forField.fill(value);
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickProfessionalDevelopment(): Promise<void> {
    await this.professional_development_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.professional_development_btn.click();
  }

  async clickDiversityEquityAndInclusion(): Promise<void> {
    await this.diversity_equity_and_inclusion_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.diversity_equity_and_inclusion_btn.click();
  }

  async clickEmployeeRecognition(): Promise<void> {
    await this.employee_recognition_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.employee_recognition_btn.click();
  }

  async clickEarlyCareer(): Promise<void> {
    await this.early_career_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.early_career_btn.click();
  }

  async clickExperiencedProfessionals(): Promise<void> {
    await this.experienced_professionals_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.experienced_professionals_btn.click();
  }

  async clickTotalRewards(): Promise<void> {
    await this.total_rewards_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.total_rewards_btn.click();
  }

  async clickNavFindAnAgency(): Promise<void> {
    await this.page.getByRole('link', { name: 'Find an Agency' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavPayMyBill(): Promise<void> {
    await this.page.getByRole('link', { name: 'Pay My Bill' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavForPolicyholders(): Promise<void> {
    await this.page.getByRole('link', { name: 'For Policyholders' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavFileAClaim(): Promise<void> {
    await this.page.getByRole('link', { name: 'File a Claim' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavReportPayroll(): Promise<void> {
    await this.page.getByRole('link', { name: 'Report Payroll' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavLocateAProvider(): Promise<void> {
    await this.page.getByRole('link', { name: 'Locate a Provider' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/careers/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
