import { Page } from '@playwright/test';

/**
 * Page Object: Commercial Construction Insurance - Amerisure
 * URL: https://amerisure.com/industries/construction/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class ConstructionPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly search_forField = this.page.locator('[name="s"]').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();

  async verifyHeading(expected = 'Commercial Construction Insurance'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearchFor(value = 'Test Value'): Promise<void> {
    await this.search_forField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_forField.fill('');
    await this.search_forField.fill(value);
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickNavFindAnAgency(): Promise<void> {
    await this.page.getByRole('link', { name: 'Find an Agency' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavPayMyBill(): Promise<void> {
    await this.page.getByRole('link', { name: 'Pay My Bill' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavForPolicyholders(): Promise<void> {
    await this.page.getByRole('link', { name: 'For Policyholders' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavFileAClaim(): Promise<void> {
    await this.page.getByRole('link', { name: 'File a Claim' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavReportPayroll(): Promise<void> {
    await this.page.getByRole('link', { name: 'Report Payroll' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavLocateAProvider(): Promise<void> {
    await this.page.getByRole('link', { name: 'Locate a Provider' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/industries/construction/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
