import { Page } from '@playwright/test';

/**
 * Page Object: Contact Us - Amerisure
 * URL: https://amerisure.com/contact-us/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class ContactUsPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly linkedinField = this.page.locator('[name="input_14"]').first();
  readonly textField = this.page.locator('input:nth-of-type(2)').first();
  readonly firstField = this.page.locator('[name="input_2.3"]').first();
  readonly lastField = this.page.locator('[name="input_2.6"]').first();
  readonly title_requiredField = this.page.locator('[name="input_8"]').first();
  readonly company_name_requiredField = this.page.locator('[name="input_9"]').first();
  readonly email_requiredField = this.page.locator('[name="input_3"]').first();
  readonly phone_requiredField = this.page.locator('[name="input_4"]').first();
  readonly message_requiredField = this.page.locator('[name="input_7"]').first();
  readonly search_forField = this.page.locator('[name="s"]').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly submit_btn = this.page.locator('button[type="submit"], input[type="submit"]').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();

  async verifyHeading(expected = 'Contact Us'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillLinkedin(value = 'Test Value'): Promise<void> {
    await this.linkedinField.waitFor({ state: 'visible', timeout: 8000 });
    await this.linkedinField.fill('');
    await this.linkedinField.fill(value);
  }

  async fillText(value = 'Test Value'): Promise<void> {
    await this.textField.waitFor({ state: 'visible', timeout: 8000 });
    await this.textField.fill('');
    await this.textField.fill(value);
  }

  async fillFirst(value = 'Test Value'): Promise<void> {
    await this.firstField.waitFor({ state: 'visible', timeout: 8000 });
    await this.firstField.fill('');
    await this.firstField.fill(value);
  }

  async fillLast(value = 'Test Value'): Promise<void> {
    await this.lastField.waitFor({ state: 'visible', timeout: 8000 });
    await this.lastField.fill('');
    await this.lastField.fill(value);
  }

  async fillTitleRequired(value = 'Test Value'): Promise<void> {
    await this.title_requiredField.waitFor({ state: 'visible', timeout: 8000 });
    await this.title_requiredField.fill('');
    await this.title_requiredField.fill(value);
  }

  async fillCompanyNameRequired(value = 'Test Value'): Promise<void> {
    await this.company_name_requiredField.waitFor({ state: 'visible', timeout: 8000 });
    await this.company_name_requiredField.fill('');
    await this.company_name_requiredField.fill(value);
  }

  async fillEmailRequired(value = 'test@example.com'): Promise<void> {
    await this.email_requiredField.waitFor({ state: 'visible', timeout: 8000 });
    await this.email_requiredField.fill('');
    await this.email_requiredField.fill(value);
  }

  async fillPhoneRequired(value = '9876543210'): Promise<void> {
    await this.phone_requiredField.waitFor({ state: 'visible', timeout: 8000 });
    await this.phone_requiredField.fill('');
    await this.phone_requiredField.fill(value);
  }

  async fillMessageRequired(value = 'Test Value'): Promise<void> {
    await this.message_requiredField.waitFor({ state: 'visible', timeout: 8000 });
    await this.message_requiredField.fill('');
    await this.message_requiredField.fill(value);
  }

  async fillSearchFor(value = 'Test Value'): Promise<void> {
    await this.search_forField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_forField.fill('');
    await this.search_forField.fill(value);
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickSubmit(): Promise<void> {
    await this.submit_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.submit_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickNavFindAnAgency(): Promise<void> {
    await this.page.getByRole('link', { name: 'Find an Agency' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavPayMyBill(): Promise<void> {
    await this.page.getByRole('link', { name: 'Pay My Bill' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavForPolicyholders(): Promise<void> {
    await this.page.getByRole('link', { name: 'For Policyholders' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavFileAClaim(): Promise<void> {
    await this.page.getByRole('link', { name: 'File a Claim' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavReportPayroll(): Promise<void> {
    await this.page.getByRole('link', { name: 'Report Payroll' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavLocateAProvider(): Promise<void> {
    await this.page.getByRole('link', { name: 'Locate a Provider' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/contact-us/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
