import { Page } from '@playwright/test';

/**
 * Page Object: File a Claim - Amerisure
 * URL: https://amerisure.com/file-a-claim/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class FileAClaimPage {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly search_forField = this.page.locator('[name="s"]').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly menu_btn = this.page.locator('button:has-text("Menu")').first();
  readonly claim_kits_btn = this.page.locator('button:has-text("Claim Kits")').first();
  readonly amerisure_insurance_company_btn = this.page.locator('button:has-text("Amerisure Insurance Company")').first();
  readonly amerisure_mutual_insurance_btn = this.page.locator('button:has-text("Amerisure Mutual Insurance")').first();
  readonly amerisure_partners_insurance_company_btn = this.page.locator('button:has-text("Amerisure Partners Insurance Company")').first();
  readonly texas_workers_compensation_network_btn = this.page.locator('button:has-text("Texas Workers’ Compensation Network")').first();
  readonly close_panel_btn = this.page.locator('button:has-text("× Close Panel")').first();

  async verifyHeading(expected = 'File a Claim'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearchFor(value = 'Test Value'): Promise<void> {
    await this.search_forField.waitFor({ state: 'visible', timeout: 8000 });
    await this.search_forField.fill('');
    await this.search_forField.fill(value);
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickMenu(): Promise<void> {
    await this.menu_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.menu_btn.click();
  }

  async clickClaimKits(): Promise<void> {
    await this.claim_kits_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.claim_kits_btn.click();
  }

  async clickAmerisureInsuranceCompany(): Promise<void> {
    await this.amerisure_insurance_company_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.amerisure_insurance_company_btn.click();
  }

  async clickAmerisureMutualInsurance(): Promise<void> {
    await this.amerisure_mutual_insurance_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.amerisure_mutual_insurance_btn.click();
  }

  async clickAmerisurePartnersInsuranceCompany(): Promise<void> {
    await this.amerisure_partners_insurance_company_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.amerisure_partners_insurance_company_btn.click();
  }

  async clickTexasWorkersCompensationNetwork(): Promise<void> {
    await this.texas_workers_compensation_network_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.texas_workers_compensation_network_btn.click();
  }

  async clickClosePanel(): Promise<void> {
    await this.close_panel_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.close_panel_btn.click();
  }

  async clickNavFindAnAgency(): Promise<void> {
    await this.page.getByRole('link', { name: 'Find an Agency' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavPayMyBill(): Promise<void> {
    await this.page.getByRole('link', { name: 'Pay My Bill' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavForPolicyholders(): Promise<void> {
    await this.page.getByRole('link', { name: 'For Policyholders' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavFileAClaim(): Promise<void> {
    await this.page.getByRole('link', { name: 'File a Claim' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavReportPayroll(): Promise<void> {
    await this.page.getByRole('link', { name: 'Report Payroll' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavLocateAProvider(): Promise<void> {
    await this.page.getByRole('link', { name: 'Locate a Provider' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto('/file-a-claim/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
