import { Page } from '@playwright/test';

/**
 * Page Object: 403 Forbidden
 * URL: https://billpay-reg.amerisure.com/
 * Generated by NAT20 Autonomous Testing Platform
 */
export class Home1Page {
  constructor(readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();

  async verifyHeading(expected = '403 Forbidden'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async navigate(): Promise<void> {
    await this.page.goto('/', { waitUntil: 'domcontentloaded' });
    await this.page.waitForLoadState('domcontentloaded');
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page
      .locator('h1, main, [role="main"], body')
      .first()
      .waitFor({ state: 'visible', timeout: 10000 });
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }
}
