import { Page } from '@playwright/test';
import { AdminLoginPage } from '../pages/AdminLoginPage';
import { CreateEditFormsPage } from '../pages/CreateEditFormsPage';
import { FormSettingsPage } from '../pages/FormSettingsPage';
import { CreateEditPagesPage } from '../pages/CreateEditPagesPage';
import { SendGenericFormPage } from '../pages/SendGenericFormPage';
import { prepareSite } from '../helpers/universal';
import { selectKendoDropdown, selectKendoDate, waitAndDismissAnyKendoAlert, fillKendoGridDates } from '../helpers/kendo';

export async function executepublishingformWorkflow(
  page: Page,
  data: Record<string, any>
) {
  await page.goto(data.startUrl || 'https://apolf-web-preprod.azurewebsites.net/Admin/AdminLogin?schoolLink=OXFORDACADEMYBANGALORE');
  await prepareSite(page);

  const adminLoginPage = new AdminLoginPage(page);
  await adminLoginPage.clickTxtusername();
  await adminLoginPage.clickLogin();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditForms', { waitUntil: 'domcontentloaded' });
  const createEditFormsPage = new CreateEditFormsPage(page);
  await createEditFormsPage.clickAddNewForm();
  await createEditFormsPage.clickNext();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/FormSettings', { waitUntil: 'domcontentloaded' });
  const formSettingsPage = new FormSettingsPage(page);
  await formSettingsPage.fillFormname('1Moulis');
  await formSettingsPage.enableFeeenabled();
  await formSettingsPage.fillAmount('3000');
  await formSettingsPage.enableRdofixed();
  await formSettingsPage.fillTransactionfee('3');
  await formSettingsPage.fillPertansactionfee('5');
  await formSettingsPage.enablePaymentplanenabled();
  await formSettingsPage.fillBtncreatepaymentplan('+ Create');
  await formSettingsPage.clickTxtpaymentplanname();
  await formSettingsPage.fillTxtpaymentplanname('MouliS1');
  await formSettingsPage.fillTxtnoofpayments('12');
  await formSettingsPage.clickNext();
  await formSettingsPage.clickTxtnoofdaysforpaymentdue();
  await formSettingsPage.fillTxtnoofdaysforpaymentdue('5');
  await formSettingsPage.fillPaymentdate('04-10-2026');
  await formSettingsPage.fillPaymentdate('04-17-2026');
  await formSettingsPage.fillPaymentdate('04-24-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('05-01-2026');
  await formSettingsPage.fillPaymentdate('05-08-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('05-09-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('05-15-2026');
  await formSettingsPage.fillPaymentdate('05-22-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('05-22-2026');
  await formSettingsPage.fillPaymentdate('05-29-2026');
  await formSettingsPage.fillPaymentdate('06-05-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('06-12-2026');
  await formSettingsPage.fillPaymentdate('');
  await formSettingsPage.fillPaymentdate('06-19-2026');
  await formSettingsPage.clickSave();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditPages**', { waitUntil: 'domcontentloaded' });
  const createEditPagesPage = new CreateEditPagesPage(page);
  await createEditPagesPage.clickAddFromExistingQuestions();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditPages**', { waitUntil: 'domcontentloaded' });
  await createEditPagesPage.clickDeselectAllRows();
  await createEditPagesPage.clickSave();
  await createEditPagesPage.clickYes();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditPages**', { waitUntil: 'domcontentloaded' });
  await createEditPagesPage.clickYes();
  await createEditPagesPage.clickYes();
  await createEditPagesPage.click1moulis();
  await createEditPagesPage.click1moulis();
  await createEditPagesPage.clickCreateEditForm();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditPages**', { waitUntil: 'domcontentloaded' });
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/CreateEditForms', { waitUntil: 'domcontentloaded' });
  await createEditFormsPage.clickSearch();
  await createEditFormsPage.fillSearch('1Moulis');
  await createEditFormsPage.clickSend();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/FormsManager/SendGenericForm', { waitUntil: 'domcontentloaded' });
  const sendGenericFormPage = new SendGenericFormPage(page);
  await sendGenericFormPage.clickDeselectAllRows();
  await sendGenericFormPage.clickRdoall();
  await sendGenericFormPage.enableRdoall();
  await sendGenericFormPage.clickPublish();
  await sendGenericFormPage.clickTxtto();
  await sendGenericFormPage.clickTxtto();
  await sendGenericFormPage.fillTxtto('testmouli4@gmail.com');
  await sendGenericFormPage.clickSend();
  await page.waitForURL('**https://apolf-web-preprod.azurewebsites.net/Admin/AdminLogin?schoolLink=OXFORDACADEMYBANGALORE', { waitUntil: 'domcontentloaded' });
}
