import { Page } from '@playwright/test';

/**
 * Page Object: Agile Consulting Services, Agile Software Development Company
 * URL: https://www.nousinfosystems.com/services/agile-development
 * Generated by NAT20 Autonomous Testing Platform
 */
export class AgileDevelopmentPage {
  constructor(readonly page: Page) {}

  readonly url = 'https://www.nousinfosystems.com/services/agile-development';
  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly your_nameField = this.page.locator('input[name="your-name"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly your_subjectField = this.page.locator('input[name="your-subject"]').first();
  readonly your_messageField = this.page.locator('textarea[name="your-message"]').first();
  readonly by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly your_emailField = this.page.locator('input[name="your-email"]').first();
  readonly previous_btn = this.page.locator('button:has-text("Previous")').first();
  readonly next_btn = this.page.locator('button:has-text("Next")').first();
  readonly _1_btn = this.page.locator('button:has-text("1")').first();
  readonly _2_btn = this.page.locator('button:has-text("2")').first();
  readonly expertise_in_agile_consulting_development_and_testing_btn = this.page.locator('button:has-text("Expertise in Agile consulting, development, and testing")').first();
  readonly in_house_developed_framework_and_metrics_btn = this.page.locator('button:has-text("In-house developed framework and metrics")').first();
  readonly best_in_class_agile_tools_btn = this.page.locator('button:has-text("Best-in-class Agile tools")').first();
  readonly well_devised_release_cycles_btn = this.page.locator('button:has-text("Well-devised release cycles")').first();

  async verifyHeading(expected = 'Deliver high-quality applications through Agile development services'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.your_nameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_nameField.fill('');
    await this.your_nameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.your_subjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_subjectField.fill('');
    await this.your_subjectField.fill(value);
  }

  async fillYourMessage(value = '25'): Promise<void> {
    await this.your_messageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_messageField.fill('');
    await this.your_messageField.fill(value);
  }

  async fillBySubmittingThisFormYouAgreeToBeContactedByNousInfosystemsViaEmailPhoneAndSmsByOptingInForTextMessagesYouConsentToReceiveAppointmentRemindersAndUpdatesAtTheNumberProvidedMessageFrequencyVariesMsgDataRatesMayApplyReplyStopToUnsubscribeOrHelpForHelpViewOurPrivacyPolicyAndTCForDetails(value = 'Test Value'): Promise<void> {
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.waitFor({ state: 'visible', timeout: 8000 });
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill('');
    await this.by_submitting_this_form_you_agree_to_be_contacted_by_nous_infosystems_via_email_phone_and_sms_by_opting_in_for_text_messages_you_consent_to_receive_appointment_reminders_and_updates_at_the_number_provided_message_frequency_varies_msg_data_rates_may_apply_reply_stop_to_unsubscribe_or_help_for_help_view_our_privacy_policy_and_t_c_for_detailsField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.your_emailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.your_emailField.fill('');
    await this.your_emailField.fill(value);
  }

  async clickPrevious(): Promise<void> {
    await this.previous_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.previous_btn.click();
  }

  async clickNext(): Promise<void> {
    await this.next_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.next_btn.click();
  }

  async click1(): Promise<void> {
    await this._1_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._1_btn.click();
  }

  async click2(): Promise<void> {
    await this._2_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this._2_btn.click();
  }

  async clickExpertiseInAgileConsultingDevelopmentAndTesting(): Promise<void> {
    await this.expertise_in_agile_consulting_development_and_testing_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.expertise_in_agile_consulting_development_and_testing_btn.click();
  }

  async clickInHouseDevelopedFrameworkAndMetrics(): Promise<void> {
    await this.in_house_developed_framework_and_metrics_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.in_house_developed_framework_and_metrics_btn.click();
  }

  async clickBestInClassAgileTools(): Promise<void> {
    await this.best_in_class_agile_tools_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.best_in_class_agile_tools_btn.click();
  }

  async clickWellDevisedReleaseCycles(): Promise<void> {
    await this.well_devised_release_cycles_btn.waitFor({ state: 'visible', timeout: 8000 });
    await this.well_devised_release_cycles_btn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async navigate(): Promise<void> {
    await this.page.goto(this.url, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'agile_development'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
