/**
 * Rename Propagation — safe cross-layer renaming for NAT 2.0 generated projects
 *
 * Two rename operations:
 *   renameLocator  — locator key in locators/*.locators.ts  → refs in pages/*.ts
 *   renameMethod   — class method in pages/*.ts             → calls in actions/business/*.ts
 *
 * Both support dryRun=true (default) to preview changes before writing.
 *
 * Pattern reference: follows the 5-layer structure generated by script-writer-agent.ts
 *   locators/XxxPage.locators.ts  →  export const XxxPageLocators = { keyName: ... }
 *   pages/XxxPage.ts              →  export class XxxPage { async methodName() { ... XxxPageLocators.keyName ... } }
 *   actions/business/xxx.ts       →  const pg = new XxxPage(page);  await pg.methodName();
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Types ────────────────────────────────────────────────────────────────────

export type RenameScope = 'locator' | 'method';

export interface RenameHit {
  file: string;     // relative path e.g. "pages/NousinfosystemsHomePage.ts"
  line: number;     // 1-based
  before: string;   // original line content (trimmed)
  after: string;    // line content after rename (trimmed)
}

export interface RenameResult {
  scope: RenameScope;
  oldName: string;
  newName: string;
  hits: RenameHit[];
  filesAffected: number;
  applied: boolean;
  error?: string;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Rename a locator key across two layers:
 *   Layer 1: locators/{locatorFile}.locators.ts  — the property key definition
 *   Layer 2: pages/*.ts                          — all ObjectName.oldKey references
 *
 * @param projectDir   Absolute path to the project root
 * @param locatorFile  Base name without extension, e.g. "NousinfosystemsHomePage"
 *                     (the locators object will be derived as "{locatorFile}Locators")
 * @param oldKey       Current locator key name, e.g. "submitButton"
 * @param newKey       New locator key name, e.g. "btnSubmit"
 * @param dryRun       true = return hits without writing (default)
 */
export function renameLocator(
  projectDir: string,
  locatorFile: string,
  oldKey: string,
  newKey: string,
  dryRun = true
): RenameResult {
  const result: RenameResult = { scope: 'locator', oldName: oldKey, newName: newKey, hits: [], filesAffected: 0, applied: false };

  try {
    // ── Layer 1: the locators file ──
    const locatorsPath = path.join(projectDir, 'locators', `${locatorFile}.locators.ts`);
    if (fs.existsSync(locatorsPath)) {
      const hits = findAndReplaceLocatorKey(locatorsPath, projectDir, oldKey, newKey, dryRun);
      result.hits.push(...hits);
    }

    // ── Layer 2: all pages/*.ts that reference the locator object ──
    const objectName = `${locatorFile}Locators`;   // e.g. NousinfosystemsHomePageLocators
    const pagesDir = path.join(projectDir, 'pages');
    if (fs.existsSync(pagesDir)) {
      for (const file of fs.readdirSync(pagesDir).filter(f => f.endsWith('.ts'))) {
        const filePath = path.join(pagesDir, file);
        const hits = findAndReplacePropertyAccess(filePath, projectDir, objectName, oldKey, newKey, dryRun);
        result.hits.push(...hits);
      }
    }

    result.filesAffected = new Set(result.hits.map(h => h.file)).size;
    result.applied = !dryRun && result.hits.length > 0;
  } catch (err: any) {
    result.error = err.message;
  }

  return result;
}

/**
 * Rename a page class method across two layers:
 *   Layer 1: pages/{pageFile}.ts             — the async method declaration
 *   Layer 2: actions/business/*.ts           — all varName.oldMethod() call sites
 *
 * @param projectDir   Absolute path to the project root
 * @param pageFile     Base name without extension, e.g. "NousinfosystemsHomePage"
 *                     (the class will be derived as "{pageFile}")
 * @param oldMethod    Current method name, e.g. "clickDataVisualizationLink"
 * @param newMethod    New method name, e.g. "navigateToDataViz"
 * @param dryRun       true = return hits without writing (default)
 */
export function renameMethod(
  projectDir: string,
  pageFile: string,
  oldMethod: string,
  newMethod: string,
  dryRun = true
): RenameResult {
  const result: RenameResult = { scope: 'method', oldName: oldMethod, newName: newMethod, hits: [], filesAffected: 0, applied: false };

  try {
    // ── Layer 1: the page class ──
    const pagePath = path.join(projectDir, 'pages', `${pageFile}.ts`);
    if (fs.existsSync(pagePath)) {
      const hits = findAndReplaceMethodDecl(pagePath, projectDir, oldMethod, newMethod, dryRun);
      result.hits.push(...hits);
    }

    // ── Layer 2: business action files that instantiate this class ──
    // Pattern: const pg = new PageClassName(page);  →  await pg.oldMethod()
    const className = pageFile;   // class name matches file name (script-writer-agent convention)
    const actionsDir = path.join(projectDir, 'actions', 'business');
    if (fs.existsSync(actionsDir)) {
      for (const file of fs.readdirSync(actionsDir).filter(f => f.endsWith('.ts'))) {
        const filePath = path.join(actionsDir, file);
        const hits = findAndReplaceMethodCalls(filePath, projectDir, className, oldMethod, newMethod, dryRun);
        result.hits.push(...hits);
      }
    }

    result.filesAffected = new Set(result.hits.map(h => h.file)).size;
    result.applied = !dryRun && result.hits.length > 0;
  } catch (err: any) {
    result.error = err.message;
  }

  return result;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/** Find and optionally replace a property key in a locators object literal */
function findAndReplaceLocatorKey(
  filePath: string,
  projectDir: string,
  oldKey: string,
  newKey: string,
  dryRun: boolean
): RenameHit[] {
  const relPath = path.relative(projectDir, filePath).replace(/\\/g, '/');
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  const hits: RenameHit[] = [];
  const newLines = [...lines];

  // Pattern: "  keyName: (page: Page): Locator =>" at the start of a property entry
  // Generated code always follows: "  keyName: (page" or "  keyName: " at 2-space indent
  const keyPattern = new RegExp(`^(\\s+)(${escapeRegex(oldKey)})(\\s*:)`);

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(keyPattern);
    if (match) {
      const replaced = lines[i].replace(keyPattern, `$1${newKey}$3`);
      hits.push({ file: relPath, line: i + 1, before: lines[i].trim(), after: replaced.trim() });
      newLines[i] = replaced;
    }
  }

  if (!dryRun && hits.length > 0) {
    fs.writeFileSync(filePath, newLines.join('\n'), 'utf-8');
  }
  return hits;
}

/** Find and optionally replace ObjectName.oldKey references (property access) */
function findAndReplacePropertyAccess(
  filePath: string,
  projectDir: string,
  objectName: string,
  oldKey: string,
  newKey: string,
  dryRun: boolean
): RenameHit[] {
  const relPath = path.relative(projectDir, filePath).replace(/\\/g, '/');
  const content = fs.readFileSync(filePath, 'utf-8');

  // Only process files that import or reference this locator object
  if (!content.includes(objectName)) return [];

  const lines = content.split('\n');
  const hits: RenameHit[] = [];
  const newLines = [...lines];

  // Pattern: ObjectName.oldKey  — always followed by ( in generated code
  const accessPattern = new RegExp(`(${escapeRegex(objectName)})\\.${escapeRegex(oldKey)}\\b`, 'g');

  for (let i = 0; i < lines.length; i++) {
    if (accessPattern.test(lines[i])) {
      const replaced = lines[i].replace(
        new RegExp(`(${escapeRegex(objectName)})\\.${escapeRegex(oldKey)}\\b`, 'g'),
        `$1.${newKey}`
      );
      hits.push({ file: relPath, line: i + 1, before: lines[i].trim(), after: replaced.trim() });
      newLines[i] = replaced;
    }
    // Reset lastIndex (global regex quirk)
    accessPattern.lastIndex = 0;
  }

  if (!dryRun && hits.length > 0) {
    fs.writeFileSync(filePath, newLines.join('\n'), 'utf-8');
  }
  return hits;
}

/** Find and optionally replace an async method declaration in a page class */
function findAndReplaceMethodDecl(
  filePath: string,
  projectDir: string,
  oldMethod: string,
  newMethod: string,
  dryRun: boolean
): RenameHit[] {
  const relPath = path.relative(projectDir, filePath).replace(/\\/g, '/');
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  const hits: RenameHit[] = [];
  const newLines = [...lines];

  // Pattern: "  async methodName(" — generated code always uses async methods with 2-space indent
  const declPattern = new RegExp(`^(\\s+async\\s+)${escapeRegex(oldMethod)}(\\s*\\()`);

  for (let i = 0; i < lines.length; i++) {
    const match = lines[i].match(declPattern);
    if (match) {
      const replaced = lines[i].replace(declPattern, `$1${newMethod}$2`);
      hits.push({ file: relPath, line: i + 1, before: lines[i].trim(), after: replaced.trim() });
      newLines[i] = replaced;
    }
  }

  if (!dryRun && hits.length > 0) {
    fs.writeFileSync(filePath, newLines.join('\n'), 'utf-8');
  }
  return hits;
}

/**
 * Find variables instantiated as `new ClassName(...)` in an actions file,
 * then find and replace all `varName.oldMethod(` call sites.
 */
function findAndReplaceMethodCalls(
  filePath: string,
  projectDir: string,
  className: string,
  oldMethod: string,
  newMethod: string,
  dryRun: boolean
): RenameHit[] {
  const relPath = path.relative(projectDir, filePath).replace(/\\/g, '/');
  const content = fs.readFileSync(filePath, 'utf-8');

  // Quick exit: file doesn't reference this class at all
  if (!content.includes(className)) return [];

  // Collect all variable names bound to `new ClassName(...)`:
  //   const pg = new NousinfosystemsHomePage(page)
  //   const pgLogin = new LoginPage(page)
  //   let myPage = new AnyPage(page)
  const instantiationPattern = new RegExp(
    `(?:const|let|var)\\s+(\\w+)\\s*=\\s*new\\s+${escapeRegex(className)}\\s*\\(`,
    'g'
  );
  const varNames: string[] = [];
  let m: RegExpExecArray | null;
  while ((m = instantiationPattern.exec(content)) !== null) {
    varNames.push(m[1]);
  }

  if (varNames.length === 0) return [];

  const lines = content.split('\n');
  const hits: RenameHit[] = [];
  const newLines = [...lines];

  for (const varName of varNames) {
    // Pattern: varName.oldMethod(  — the dot-call syntax
    const callPattern = new RegExp(`(${escapeRegex(varName)})\\.${escapeRegex(oldMethod)}\\b`, 'g');

    for (let i = 0; i < lines.length; i++) {
      if (callPattern.test(lines[i])) {
        const replaced = newLines[i].replace(
          new RegExp(`(${escapeRegex(varName)})\\.${escapeRegex(oldMethod)}\\b`, 'g'),
          `$1.${newMethod}`
        );
        hits.push({ file: relPath, line: i + 1, before: lines[i].trim(), after: replaced.trim() });
        newLines[i] = replaced;
      }
      callPattern.lastIndex = 0;
    }
  }

  if (!dryRun && hits.length > 0) {
    fs.writeFileSync(filePath, newLines.join('\n'), 'utf-8');
  }
  return hits;
}

/** Escape special regex characters in a string */
function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
