import { Page } from '@playwright/test';

/**
 * Page Object: Agile Consulting Services, Agile Software Development Company
 * URL: https://www.nousinfosystems.com/services/agile-development
 * Generated by NAT20 Autonomous Testing Platform
 */
export class AgileDevelopmentPage {
  constructor(private readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly yourNameField = this.page.locator('input[name="your-name"]').first();
  readonly yourEmailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly yourSubjectField = this.page.locator('input[name="your-subject"]').first();
  readonly yourMessageField = this.page.locator('textarea[name="your-message"]').first();
  readonly consentCheckboxField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly previousBtn = this.page.locator('button:has-text("Previous")').first();
  readonly nextBtn = this.page.locator('button:has-text("Next")').first();
  readonly btn1 = this.page.locator('button:has-text("1")').first();
  readonly btn2 = this.page.locator('button:has-text("2")').first();
  readonly expertiseInAgileBtn = this.page.locator('button:has-text("Expertise in Agile consulting, development, and testing")').first();
  readonly inHouseFrameworkBtn = this.page.locator('button:has-text("In-house developed framework and metrics")').first();
  readonly bestInClassAgileToolsBtn = this.page.locator('button:has-text("Best-in-class Agile tools")').first();
  readonly wellDevisedReleaseCyclesBtn = this.page.locator('button:has-text("Well-devised release cycles")').first();

  async navigate(): Promise<void> {
    await this.page.goto('/services/agile-development', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page.locator('h1, h2, .page-title, [class*="hero"]').first().waitFor({ state: 'visible', timeout: 15000 });
  }

  async verifyHeading(expected = 'Deliver high-quality applications'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.yourNameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourNameField.fill('');
    await this.yourNameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.yourEmailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourEmailField.fill('');
    await this.yourEmailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.yourSubjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourSubjectField.fill('');
    await this.yourSubjectField.fill(value);
  }

  async fillYourMessage(value = 'Test message content'): Promise<void> {
    await this.yourMessageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourMessageField.fill('');
    await this.yourMessageField.fill(value);
  }

  async clickPrevious(): Promise<void> {
    await this.previousBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.previousBtn.click();
  }

  async clickNext(): Promise<void> {
    await this.nextBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.nextBtn.click();
  }

  async clickExpertiseInAgileConsultingDevelopmentAndTesting(): Promise<void> {
    await this.expertiseInAgileBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.expertiseInAgileBtn.click();
  }

  async clickInHouseDevelopedFrameworkAndMetrics(): Promise<void> {
    await this.inHouseFrameworkBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.inHouseFrameworkBtn.click();
  }

  async clickBestInClassAgileTools(): Promise<void> {
    await this.bestInClassAgileToolsBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.bestInClassAgileToolsBtn.click();
  }

  async clickWellDevisedReleaseCycles(): Promise<void> {
    await this.wellDevisedReleaseCyclesBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.wellDevisedReleaseCyclesBtn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'agile_development'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
