import { Page } from '@playwright/test';

/**
 * Page Object: Careers - Nous
 * URL: https://www.nousinfosystems.com/careers
 * Generated by NAT20 Autonomous Testing Platform
 */
export class CareersPage {
  constructor(private readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly text917Field = this.page.locator('input[name="text-917"]').first();
  readonly yearOfExperienceField = this.page.locator('input[name="year-of-experience"]').first();
  readonly aboutYouField = this.page.locator('textarea[name="about-you"]').first();
  readonly file555Field = this.page.locator('input[name="file-555"]').first();
  readonly yourNameField = this.page.locator('input[name="your-name"]').first();
  readonly yourEmailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly yourSubjectField = this.page.locator('input[name="your-subject"]').first();
  readonly yourMessageField = this.page.locator('textarea[name="your-message"]').first();
  readonly consentCheckboxField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly experiencedProfessionalsBtn = this.page.locator('button:has-text("Experienced Professionals")').first();
  readonly earlyCareersBtn = this.page.locator('button:has-text("Early Careers and Campus Program")').first();
  readonly submitBtn = this.page.locator('button[type="submit"], input[type="submit"]').first();

  async navigate(): Promise<void> {
    await this.page.goto('/careers', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page.locator('h1, h2, .page-title, [class*="hero"]').first().waitFor({ state: 'visible', timeout: 15000 });
  }

  async verifyHeading(expected = 'Build'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillText917(value = 'Test Value'): Promise<void> {
    await this.text917Field.waitFor({ state: 'visible', timeout: 8000 });
    await this.text917Field.fill('');
    await this.text917Field.fill(value);
  }

  async fillYearOfExperience(value = 'Test Value'): Promise<void> {
    await this.yearOfExperienceField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yearOfExperienceField.fill('');
    await this.yearOfExperienceField.fill(value);
  }

  async fillAboutYou(value = 'Test Value'): Promise<void> {
    await this.aboutYouField.waitFor({ state: 'visible', timeout: 8000 });
    await this.aboutYouField.fill('');
    await this.aboutYouField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.yourNameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourNameField.fill('');
    await this.yourNameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.yourEmailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourEmailField.fill('');
    await this.yourEmailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.yourSubjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourSubjectField.fill('');
    await this.yourSubjectField.fill(value);
  }

  async fillYourMessage(value = 'Test message content'): Promise<void> {
    await this.yourMessageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourMessageField.fill('');
    await this.yourMessageField.fill(value);
  }

  async clickExperiencedProfessionals(): Promise<void> {
    await this.experiencedProfessionalsBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.experiencedProfessionalsBtn.click();
  }

  async clickEarlyCareersAndCampusProgram(): Promise<void> {
    await this.earlyCareersBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.earlyCareersBtn.click();
  }

  async clickSubmit(): Promise<void> {
    await this.submitBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.submitBtn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'careers'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
