import { Page } from '@playwright/test';

/**
 * Page Object: Quality Engineering Services | Software Quality Engineering
 * URL: https://www.nousinfosystems.com/services/quality-engineering
 * Generated by NAT20 Autonomous Testing Platform
 */
export class QualityEngineeringPage {
  constructor(private readonly page: Page) {}

  readonly heading = this.page.locator('h1').first();
  readonly searchField = this.page.locator('input[name="s"]').first();
  readonly yourNameField = this.page.locator('input[name="your-name"]').first();
  readonly yourEmailField = this.page.locator('input[name="your-email"]').first();
  readonly contactnumberField = this.page.locator('#phoneNumberInput').first();
  readonly yourSubjectField = this.page.locator('input[name="your-subject"]').first();
  readonly yourMessageField = this.page.locator('textarea[name="your-message"]').first();
  readonly consentCheckboxField = this.page.locator('input[name="checkbox-815[]"]').first();
  readonly previousBtn = this.page.locator('button:has-text("Previous")').first();
  readonly nextBtn = this.page.locator('button:has-text("Next")').first();
  readonly btn1 = this.page.locator('button:has-text("1")').first();
  readonly btn2 = this.page.locator('button:has-text("2")').first();
  readonly years25ExperienceBtn = this.page.locator('button:has-text("25+ years of experience in the software industry")').first();
  readonly inHouseRDLabsBtn = this.page.locator('button:has-text("In-house R&D labs, test automation framework")').first();
  readonly strongPartnershipBtn = this.page.locator('button:has-text("Strong partnership with best-in-class testing tools")').first();
  readonly reusableAssetsBtn = this.page.locator('button:has-text("Reusable assets for the quick and easy adoption")').first();

  async navigate(): Promise<void> {
    await this.page.goto('/services/quality-engineering', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => {});
  }

  async waitForPageLoad(): Promise<void> {
    await this.page.waitForLoadState('domcontentloaded');
    await this.page.locator('h1, h2, .page-title, [class*="hero"]').first().waitFor({ state: 'visible', timeout: 15000 });
  }

  async verifyHeading(expected = 'Scalable quality engineering services'): Promise<void> {
    await this.heading.waitFor({ state: 'visible', timeout: 10000 });
    const text = await this.heading.textContent();
    if (!text?.includes(expected)) {
      throw new Error('Expected heading to contain "' + expected + '" but got: ' + text);
    }
  }

  async fillSearch(value = 'Test Value'): Promise<void> {
    await this.searchField.waitFor({ state: 'visible', timeout: 8000 });
    await this.searchField.fill('');
    await this.searchField.fill(value);
  }

  async fillYourName(value = 'John Doe'): Promise<void> {
    await this.yourNameField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourNameField.fill('');
    await this.yourNameField.fill(value);
  }

  async fillYourEmail(value = 'test@example.com'): Promise<void> {
    await this.yourEmailField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourEmailField.fill('');
    await this.yourEmailField.fill(value);
  }

  async fillContactnumber(value = '9876543210'): Promise<void> {
    await this.contactnumberField.waitFor({ state: 'visible', timeout: 8000 });
    await this.contactnumberField.fill('');
    await this.contactnumberField.fill(value);
  }

  async fillYourSubject(value = 'Test Subject'): Promise<void> {
    await this.yourSubjectField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourSubjectField.fill('');
    await this.yourSubjectField.fill(value);
  }

  async fillYourMessage(value = 'Test message content'): Promise<void> {
    await this.yourMessageField.waitFor({ state: 'visible', timeout: 8000 });
    await this.yourMessageField.fill('');
    await this.yourMessageField.fill(value);
  }

  async clickPrevious(): Promise<void> {
    await this.previousBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.previousBtn.click();
  }

  async clickNext(): Promise<void> {
    await this.nextBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.nextBtn.click();
  }

  async click25YearsOfExperienceInTheSoftwareIndustry(): Promise<void> {
    await this.years25ExperienceBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.years25ExperienceBtn.click();
  }

  async clickInHouseRDLabsTestAutomationFramework(): Promise<void> {
    await this.inHouseRDLabsBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.inHouseRDLabsBtn.click();
  }

  async clickStrongPartnershipWithBestInClassTestingTools(): Promise<void> {
    await this.strongPartnershipBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.strongPartnershipBtn.click();
  }

  async clickReusableAssetsForTheQuickAndEasyAdoption(): Promise<void> {
    await this.reusableAssetsBtn.waitFor({ state: 'visible', timeout: 8000 });
    await this.reusableAssetsBtn.click();
  }

  async clickNavNews(): Promise<void> {
    await this.page.getByRole('link', { name: 'News' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavEvents(): Promise<void> {
    await this.page.getByRole('link', { name: 'Events' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavCareers(): Promise<void> {
    await this.page.getByRole('link', { name: 'Careers' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavContactUs(): Promise<void> {
    await this.page.getByRole('link', { name: 'Contact Us' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalProductEngineering(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Product Engineering' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavAgileDevelopment(): Promise<void> {
    await this.page.getByRole('link', { name: 'Agile Development' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async clickNavDigitalApplicationServices(): Promise<void> {
    await this.page.getByRole('link', { name: 'Digital Application Services' }).first().click();
    await this.page.waitForLoadState('domcontentloaded');
  }

  async getTitle(): Promise<string> {
    return this.page.title();
  }

  async takeScreenshot(name?: string): Promise<void> {
    await this.page.screenshot({
      path: `screenshots/${name ?? 'quality_engineering'}-${Date.now()}.png`,
      fullPage: true,
    });
  }
}
